////

|metadata|
{
    "name": "breaking-changes-2009-volume-2",
    "controlName": [],
    "tags": ["Known Issues"],
    "guid": "{40005137-84DC-4FF4-9830-80BFCAEC3645}",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:16:05.5587968Z"
}
|metadata|
////

= 2009 Volume 2

== xamMap

xamMap コントロールの Projection プロパティは名前が link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.xammap~mapprojection.html[MapProjection] に変更されました。これに加えて ProjectionType プロパティは link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.xammap~mapprojectiontype.html[MapProjectionType] に変更されました。またデフォルトのマップ プロジェクト タイプは link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.projectiontype.html[SphericalMercator] に変更されました。

xamDock コントロールは Infragistics.Controls アセンブリおよび名前空間に移動されました。その結果、 link:{ApiPlatform}datavisualization{ApiVersion}~infragistics.controls.xamdock.html[xamDock] に関連する属性は以下の通りに変更されます:

xamDock コントロールを使用して link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.mapnavigationpane.html[MapNavigationPane] をドッキングするための新しいメソッド:

*XAML の場合:*

----
xmlns:igMap="clr-namespace:Infragistics.Controls.Maps;assembly={ApiPlatform}Controls.Maps.XamMap.v9.2" 
xmlns:ig="clr-namespace:Infragistics.Controls.;assembly={ApiPlatform}DataVisualization.v9.2" 
<!-- ...-->
igMap:MapNavigationPane Margin="10" ig:XamDock.Edge="InsideRight"
----

== xamTimeline

xamTimeline コントロールの PreventOverlapping プロパティは削除されました。また link:{ApiPlatform}controls.timelines.xamtimeline{ApiVersion}~infragistics.controls.timelines.eventtitle~linestyle.html[LineStyle] と呼ばれる新しいプロパティが link:{ApiPlatform}controls.timelines.xamtimeline{ApiVersion}~infragistics.controls.timelines.eventtitle.html[EventTitle] オブジェクトのテンプレートに追加されました。このプロパティにより EventTitle を Timeline 軸と結ぶ線のスタイルは変更可能となり、以下は EventTitle のデフォルトのテンプレートです:

*XAML の場合:*        

[source]
----
xmlns:igtl="clr-namespace:Infragistics.Controls.Timelines;assembly={ApiPlatform}Controls.Timelines.XamTimeline.v9.2"
        <!-- EventTitle テンプレートによって使用されるリソース -->
        <LinearGradientBrush x:Key="EventTitleBackgroundBrush" StartPoint="0,0" EndPoint="0,1">
            <LinearGradientBrush.GradientStops>
                <GradientStopCollection>
                    <GradientStop Offset="0" Color="#FFffffff"
                    <GradientStop Offset="1" Color="#FFeff1f3"
                </GradientStopCollection>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
        <LinearGradientBrush x:Key="EventTitleBorderBrush" StartPoint="0,0" EndPoint="0,1">
            <LinearGradientBrush.GradientStops>
                <GradientStopCollection>
                    <GradientStop Color="#FFa3aeb9" Offset="0"
                    <GradientStop Color="#FF8399a9" Offset="0.3700000047683716"
                    <GradientStop Color="#FF718597" Offset="0.3709999918937683"
                    <GradientStop Color="#FF617584" Offset="1"
                </GradientStopCollection>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
        <!-- デフォルトの EventTitle テンプレート -->
        <Style TargetType="igtl:EventTitle">
            <Setter Property="MaxWidth" Value="180" 
            <Setter Property="IsTabStop" Value="
            <Setter Property="Background" Value="{StaticResource EventTitleBackgroundBrush}" 
            <Setter Property="Foreground" Value="#FF333333"
            <Setter Property="BorderThickness" Value="1" 
            <Setter Property="BorderBrush" Value="{StaticResource EventTitleBorderBrush}" 
            <Setter Property="PointStringFormat" Value="{}[{0}]" 
            <Setter Property="SpanStringFormat" Value="{}[{0}-{1}]" 
            <Setter Property="Padding" Value="5"
            <Setter Property="LineStyle">
                <Setter.Value>
                    <Style TargetType="Line">
                        <Setter Property="StrokeThickness" Value="1" 
                        <Setter Property="Stroke" Value="{StaticResource EventTitleBorderBrush}" 
                        <Setter Property="Canvas.ZIndex" Value="-1" 
                        <Setter Property="Margin" Value="0,3,0,0" 
                        <Setter Property="UseLayoutRounding" Value="True" 
                    </Style>
                </Setter.Value>
            </Setter>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="igtl:EventTitle">
                        <Border BorderThickness="0,0,1,1" 
                                BorderBrush="#59617583" 
                                CornerRadius="4">
                            <Border HorizontalAlignment="Left"
                                    BorderThickness="{TemplateBinding BorderThickness}"
                                    Background="{TemplateBinding Background}"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    CornerRadius="3"
                                    UseLayoutRounding="True">
                                <Grid>
                                    <Border BorderBrush="#FFFFFFFF" 
                                            BorderThickness="1" 
                                            CornerRadius="2" 
                                    <Grid Margin="{TemplateBinding Padding}">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="*" 
                                            <RowDefinition Height="Auto" 
                                        </Grid.RowDefinitions>
                                        <TextBlock Text="{TemplateBinding FormattedText}"
                                                           TextWrapping="Wrap" 
                                        <TextBlock Text="{TemplateBinding Title}" 
                                                         TextWrapping="Wrap" 
                                                         Grid.Row="1"
                                    </Grid>
                                </Grid>
                            </Border>
                        </Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
----

== xamLinearGauge および xamRadialGauge

xamLinearGauge コントロールと xamRadialGauge コントロールの以下のオブジェクトのための ValueChanged イベントのタイプは EventHandler から ValueChangedEventArgs に変更されました。

* Infragistics.Controls.Charts.GaugeBarMarkerBase のための ValueChanged

*Visual Basic の場合:*

----
AddHandler Me.xamLinearGauge.Scales(0).BarMarkers(0).ValueChanged, AddressOf LinearGaugeBarMarker_ValueChanged
Private Sub LinearGaugeBarMarker_ValueChanged(ByVal sender As Object, ByVal e As Infragistics.Controls.Charts.ValueChangedEventArgs)
        Dim newValue As Double = e.NewValue
End Sub
----

*C# の場合:*

----
this.xamLinearGauge.Scales[0].BarMarkers[0].ValueChanged += LinearGaugeBarMarker_ValueChanged;
private void LinearGaugeBarMarker_ValueChanged(object sender, Infragistics.Controls.Charts.ValueChangedEventArgs e)
{
    double newValue = e.NewValue;
}
----

* Infragistics.Controls.Charts.GaugeNeedleBase のための ValueChanged

*Visual Basic の場合:*

----
AddHandler Me.xamLinearGauge.Scales(0).Needles(0).ValueChanged, AddressOf LinearGaugeNeedle_ValueChanged
Private Sub LinearGaugeNeedle_ValueChanged(ByVal sender As Object, ByVal e As Infragistics.Controls.Charts.ValueChangedEventArgs)
    Dim newValue As Double = e.NewValue
End Sub
----

*C# の場合:*

----
this.xamLinearGauge.Scales[0].Needles[0].ValueChanged += LinearGaugeNeedle_ValueChanged;
private void LinearGaugeNeedle_ValueChanged(object sender, Infragistics.Controls.Charts.ValueChangedEventArgs e)
{
    double newValue = e.NewValue;
}
----

* Infragistics.Controls.Charts.RadialGaugeNeedle のための ValueChanged

*Visual Basic の場合:*

----
AddHandler Me.xamRadialGauge.Scales(0).Needles(0).ValueChanged, AddressOf RadialGaugeNeedle_ValueChanged
Private Sub RadialGaugeNeedle_ValueChanged(ByVal sender As Object, ByVal e As Infragistics.Controls.Charts.ValueChangedEventArgs)
    Dim newValue As Double = e.NewValue
End Sub
----

*C# の場合:*

----
this.xamRadialGauge.Scales[0].Needles[0].ValueChanged += RadialGaugeNeedle_ValueChanged;
private void RadialGaugeNeedle_ValueChanged(object sender, Infragistics.Controls.Charts.ValueChangedEventArgs e)
{
    double newValue = e.NewValue;
}
----