////

|metadata|
{
    "name": "control-persistence-framework",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["Getting Started","Persistence"],
    "guid": "{7A949FAA-D54D-4B8B-8444-EDB4F6106B69}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5360358Z"
}
|metadata|
////

= Infragistics Control Persistence Framework

このセクションは、 link:{ApiPlatform}persistence{ApiVersion}~infragistics.persistence_namespace.html[Infragistics Persistence Framework]™ ライブラリの使用に関する概要を提供します。このセクションには、Infragistics Control Persistence Framework が何を実行するのか、またアプリケーションでなぜこれを使用したくなるのかから、ライブラリを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、Infragistics Control Persistence Framework に関する貴重な情報が含まれています。

以下のリンクをクリックして Infragistics Control Persistence Framework に関する重要情報にアクセスします。

== link:persistence-about-ig-control-persistence-framework.html[Infragistics Control Persistence Framework について]

このセクションの説明を読むと、Infragistics Control Persistence Framework コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

pick:[sl,wpf="== link:persistenceframework-getting-started-with-infragistics-control-persistence-framework.html[Infragistics Control Persistence Framework を使用した作業の開始]"]

ifdef::sl,wpf[]
Infragistics Control Persistence Framework を使用してできる限り素早く起動して実行するために、作業を開始する方法についての情報を提供します。
endif::sl,wpf[]

pick:[win-phone="== link:569d7d98-f246-4513-8a87-7e9b1b52c352[Infragistics Control Persistence Framework を使用した、オブジェクトの設定の保持]"]

ifdef::win-phone[]
Infragistics Control Persistence Framework を使用してできる限り素早く起動して実行するために、作業を開始する方法についての情報を提供します。
endif::win-phone[]

== link:persistence-using-ig-control-persistence-framework.html[Infragistics Control Persistence Framework の使用]

このセクションには、Infragistics Control Persistence Framework で提供される主要な特徴および機能についての情報が含まれています。

== link:persistence-api-overview.html[API の概要]

このトピックでは、Infragistics Control Persistence Framework を使用したプログラミング中に扱う名前空間とクラスを説明します。このトピックの名前空間とクラスの一覧は、{ProductName} ヘルプの API 参照ガイドへリンクします。