////

|metadata|
{
    "name": "developers-guide-ui-automation-overview",
    "controlName": [],
    "tags": [],
    "guid": "f837a5c6-c444-44fd-b966-d6d1363b7e0d",  
    "buildFlags": ["wpf"],
    "createdOn": "2012-01-30T20:06:59.271777Z"
}
|metadata|
////

= UI オートメーションの概要

{ProductName} コントロールは、Microsoft Windows® の新しいアクセシビリティ フレームワークである link:https://msdn.microsoft.com/ja-jp/library/windows/desktop/ee684009[Microsoft® UI Automation] をサポートします。このフレームワークは、Windows Presentation Foundation (WPF) をサポートするすべてのオペレーティングシステムで使用できます。このトピックでは、特定のコントロールとそれらの制限によってサポートされる自動化を説明します。

xamMaskedEditor™ コントロールと xamTextEditor™ コントロールは Value コントロール パターンをサポートします。これによって、それらの値を読み取り変更することが可能となります。

xamMaskedEditor は、ITextProvider コントロール パターンをサポートします。ITextProvider コントロール パターンを使用して以下を実行できます:

* コントロール内のテキストに関する情報を取得
* 選択したテキストを検索
* 選択されているテキストを変更
* テキストを指定

[NOTE]
====
*注:*  xamTextEditor コントロールはこの機能を取得するために ITextProvider を実装する必要はありません。編集モードの間に xamTextEditor 内に含まれる TextBox はこのインタフェースをサポートします。
====

xamCheckEditor™ コントロールは Toggle コントロール パターンをサポートします。これによってチェックされた状態を読み取り変更することが可能となります。

DataPresenterBase クラスとすべての派生コントロール (例: xamDataGrid™、xamDataCarousel™、および xamDataPresenter™) は以下をサポートします:

* ブレッドクラムは Invoke コントロール パターンをサポートします。これによって、ブレッドクラム アクションを呼び出すことが可能となります (特定の親レコードにナビゲート)。
* セルは Value コントロール パターンをサポートします。これによって、値を読み取って変更することが可能となります。
* セルは SelectionItem コントロール パターンをサポートします。これによって、選択するまたは選択を解除することが可能となります。
* セルはセルを表示する ScrollItem コントロール パターンをサポートします。
* セルは GridItem および TableItem コントロール パターンをサポートします。これによってセルの行/列の位置情報を取得することが可能となります。
* GroupByArea は ExpandCollapse コントロール パターンをサポートします。これによって自動化によって領域を展開/縮小することが可能となります。
* フィールド ラベルは Invoke コントロール パターンをサポートします。これによって列のソートを切り替えることが可能となります。
* レコードは ExpandCollapse コントロール パターンをサポートします。これによって自動化はその展開状態を判断して変更することが可能となります。
* レコードは ScrollItem コントロール パターンをサポートします。これによって自動化はレコードを表示することが可能となります。
* レコードは SelectionItem コントロール パターンをサポートします。これによって自動化はレコードを選択/選択を解除することが可能となります。
* レコード リスト (レコードを管理するリスト コントロール) は Selection コントロール パターンを実装します。Selection コントロール パターンは選択した項目のリストを取得します。
* DataRecords に関連づけられたレコード リストは Grid および Table コントロール パターンもサポートします。これらのコントロール パターンは、行/列ヘッダだけでなく、行/列情報を取得します。
* ルート レコード リストは Scroll コントロール パターンをサポートします。

== 既知の制限

以下は現在確認されているアクセシビリティの制限リストです。

* セルおよびフィールド ラベルは Transform コントロール パターンを実装しません。これによって、自動化による列/セル/行のサイズ変更は不可能になります。
* フィールド ラベルは選択パターンを実装しないため、自動化によって列を選択することが不可能になります。