////

|metadata|
{
    "name": "developers-guide-upgrading-your-project",
    "controlName": [],
    "tags": ["How Do I"],
    "guid": "e7379b1a-1668-4978-b481-c65454c8eed6",  
    "buildFlags": ["wpf","sl"],
    "createdOn": "2012-01-30T15:17:19.5645983Z"
}
|metadata|
////

= プロジェクトのアップグレード

{ProductName} 2010 Volume 2 リリース以前は、インフラジスティックスは WPF コントロールと Silverlight コントロールを別々に開発していました。その結果、各プラットフォームのタイプ、名前空間、およびアセンブリの名前は必ずしも一致しておらず、2 つのプラットフォーム間でコードをほとんど共有できませんでした。SL コンポーネントと WPF コンポーネントのために統一された基礎を構築するために、短期間でアプリケーションに影響を及ぼす重要な変更を行う必要がありました。ただし、これらの変更によって開発者は大きな恩恵を受けられます。

* 学習の活用 - ひとつのプラットフォームのコントロールを学習すれば、他のプラットフォームのコントロールを学習したことになります。
* WPF および Silverlight アプリケーション間でソースコードを共有および再使用することが簡単になります。
* WPF アプリケーションと Silverlight 間で素早く移植できます。
* WPF および Silverlight に弊社が提供する UI コントロール間は非常に似ているため、同時に両方のプラットフォームに対して新しいコントロールおよび機能がリリースされます。
* プラットフォーム間で素早くソリューションを提供することを可能にすることによって、顧客のニーズをより簡単に満たすことができます。

*サポート*

本トピックで説明したように、以前の {ProductName} アプリケーションのアップグレードには、いくつかの手順が必要となります。手順は簡単であるため問題は起こらないはずです。万一問題が起こった場合は、サポートにお問い合わせください。最優先でサポートいたします。次の手順を実行します

[start=1]
. 以降のリンクをクリックしてください。

link:https://jp.infragistics.com/Login.aspx?ReturnUrl=%2fSupport%2fSubmitSupportIssue.aspx[https://jp.infragistics.com/Login.aspx?ReturnUrl=%2fSupport%2fSubmitSupportIssue.aspx]
[start=2]
. *サマリーのタイトルに NAMESPACE と記入してください。* 1 営業日内に開発サポート チームからご連絡させていただきます。

== 関連トピック

link:developers-guide-restoring-version-upgrade-utility-backup-undoing-upgrade.html[バージョン アップグレード ユーティリティ バックアップの復元]

link:developers-guide-upgrading-to-11-1-using-version-utility.html[バージョン ユーティリティを使用してプロジェクトを {ProductNameVersion} へアップグレード]