////

|metadata|
{
    "name": "generalconcepts-assemblies",
    "controlName": [],
    "tags": [],
    "guid": "fee36866-529f-4d32-a69c-c60504965bac",  
    "buildFlags": [],
    "createdOn": "2012-01-31T16:13:29.3453347Z"
}
|metadata|
////

= アセンブリ

アセンブリは、共通言語ランタイム (CLR) のコア部分です。これは、アプリケーションを実行するために CLR が必要とするタイプとリソースの集合で、通常はひとつの実行可能ファイル (.exe) または DLL (dynamic-link library) の形で格納されています。アセンブリは、配備、バージョンコントロール、セキュリティのパーミッションを含むアプリケーションの重要な側面を制御します。

{ProductName} アセンブリの詳細は、下記のリンクをクリックしてください。

==== link:netadvantage-assemblies.html[{ProductName} アセンブリ]

このトピックでは、{ProductName} 製品に含まれるすべてのアセンブリのリストと、それらのアセンブリに対応するコントロールおよびコンポーネントについて紹介します。

==== link:default-xml-namespace-mappings.html[XML 名前空間のデフォルト マッピング]

このトピックでは、{ProductName} 製品に含まれているアセンブリのすべてのデフォルトの XML 名前空間マッピングをリストします。

==== link:adding-assembly-to-a-visual-studio-project.html[アセンブリを Visual Studio プロジェクトに追加]

このトピックでは、{ProductName} アセンブリを Microsoft Visual Studio® .NET プロジェクトに簡単に追加する方法について説明します。

==== link:adding-an-assembly-to-an-expression-blend-project.html[アセンブリを Expression Blend プロジェクトに追加]

このトピックでは、{ProductName} アセンブリを Microsoft Expression® Blend プロジェクトに簡単に追加する方法について説明します。

==== link:generalconcepts-signed-andunsigned-assemblies.html[署名済みのアセンブリと未署名のアセンブリ]

このトピックでは、署名済みおよび未署名のアセンブリをいつ使用するかについて説明します。

==== link:version-free-assemblies.html[バージョンフリー アセンブリ]

このトピックでは、バージョンフリーなアセンブリーを使用するメリットを示す考え方を紹介します。