////

|metadata|
{
    "name": "ig-calculators-fixed-value-calculator",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "949e4db7-ce41-45a7-8b87-4b65d421e840",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7340386Z"
}
|metadata|
////

= Infragistics 固定値計算式

このトピックは link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ ライブラリの一部である link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] を紹介します。

== 概要

トピックは以下のとおりです。

* <<Introduction,概要>>
* <<Properties,プロパティ>>
* <<Requirements,要件>>
* <<Example,例>>
* <<RelatedTopics,関連トピック>>

== 概要

link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] は link:datachart-datachart.html[xamDataChart]™ コントロールの中の Series オブジェクトに対する誤差範囲の値を生成するのに使います。

== 固定値計算プロパティ

このセクションでは link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] クラスのプロパティのリストを提供します。

[options="header", cols="a,a,a"]
|====
|プロパティ名|プロパティ タイプ|説明

|Value
|double
|誤差範囲の長さを生成するための値を取得または設定します。

|====

== 要件

FixedValueCalculator を使用するためには、次の NuGet パッケージ参照を {PlatformName} プロジェクトに追加する必要があります。

** Infragistics.WPF.Math.Calculators

NuGet フィードのセットアップと NuGet パッケージの追加の詳細については、link:nuget-feeds.html[NuGet フィード] ドキュメントを参照してください。

== 例

Series オブジェクトの固定長で誤差範囲を計算するために、FixedValueCalculator を xamDataChart コントロールに統合する方法を例示する link:datachart-series-error-bars.html[シリーズ誤差範囲] トピックを参照してください。

== 関連トピック

* link:ig-math-calculators-api-overview.html[API の概要]
* link:datachart-series-error-bars.html[シリーズ誤差範囲]