////

|metadata|
{
    "name": "ig-calculators-data-calculator",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "4405c663-39ab-43ac-a132-f92d005c3455",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7280367Z"
}
|metadata|
////

= Infragistics データ計算式

このトピックは link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ ライブラリの一部である link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] を紹介します。

== 概要

トピックは以下のとおりです。

* <<Introduction,概要>>
* <<Properties,プロパティ>>
* <<Requirements,要件>>
* <<Example,例>>
* <<RelatedTopics,関連トピック>>

== 概要

link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] は link:datachart-datachart.html[xamDataChart] コントロールの中の Series オブジェクトに対するカスタム誤差範囲を作成するのに使います。

== プロパティ

このセクションでは link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] クラスのプロパティのリストを提供します。

[options="header", cols="a,a,a"]
|====
|プロパティ名|プロパティ タイプ|説明

| link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.itemssourcecalculator~itemssource.html[ItemsSource]
| link:http://msdn.microsoft.com/ja-jp/library/system.collections.ienumerable.aspx[IEnumerable]
|計算のためのデータ項目のソースを取得または設定します。

| link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.itemssourcecalculator~valuememberpath.html[ValueMemberPath]
|string
|データ項目の Value メンバー パスを取得または設定します。このプロパティはデータ項目の数値プロパティの名前にマップされなければなりません。

|====

== 要件

DataCalculator を使用するためには、次の NuGet パッケージ参照を {PlatformName} プロジェクトに追加する必要があります。

** Infragistics.WPF.Math.Calculators

NuGet フィードのセットアップと NuGet パッケージの追加の詳細については、link:nuget-feeds.html[NuGet フィード] ドキュメントを参照してください。

== 例

Series オブジェクトのカスタム長で誤差範囲を作成するために、DataCalculator を xamDataChart コントロールに統合する方法を例示する link:datachart-series-error-bars.html[シリーズ誤差範囲]トピックを参照してください。

== 関連トピック

* link:ig-math-calculators-api-overview.html[API の概要]
* link:datachart-series-error-bars.html[シリーズ誤差範囲]