////

|metadata|
{
    "name": "ig-math-matrices",
    "controlName": ["IG Math Library"],
    "tags": ["Calculations"],
    "guid": "3e6a39d0-e3c0-42af-afd8-517332954f08",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.8400513Z"
}
|metadata|
////

= 行列

Infragistics Math Library は行列での作業のために機能を提供します。

== 行列について

行列はオブジェクトのコレクションを保存するための多次元のデータ クラスです。概念の詳細は、 link:http://ja.wikipedia.org/wiki/%E8%A1%8C%E5%88%97[Matrix] ウェブサイトを参照してください。

== 行列の使用

Infragistics Math Library は以下の行列クラスをサポートします。

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrix.html[Matrix] - 実数のコレクションを保存します
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanmatrix.html[BooleanMatrix] - ブール値のコレクションを保存します
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexmatrix.html[ComplexMatrix] - 複素数のコレクションを保存します

これらのクラスはすべて link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] クラスから派生します。これらは保存するデータ タイプが異なります。

以下のトピックは、Infragistics Math Library で行列を使用する方法を説明します。

* link:ig-math-creating-matrices.html[行列の作成]
* link:ig-math-working-with-matrices.html[行列での作業]

== 関連トピック

link:ig-math-complex-numbers.html[複素数]

link:ig-math-vectors.html[ベクトル]

link:ig-math-mathematical-functions.html[数学関数]