////

|metadata|
{
    "name": "ig-math-vectors",
    "controlName": ["IG Math Library"],
    "tags": ["Calculations"],
    "guid": "8abbae9b-15ca-46db-8038-9235d13ada66",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.8480846Z"
}
|metadata|
////

= ベクトル

Infragistics Math Library はベクトルでの作業のために機能を提供します。

== ベクトルについて

ベクトルはオブジェクトのコレクションを保存するための 1 次元のデータ クラスです。link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] は link:http://en.wikipedia.org/wiki/Row_vector[行ベクトル]または link:http://en.wikipedia.org/wiki/Column_vector[列ベクトル]にすることができます。

== ベクトルの使用

Infragistics Math Library は以下のベクトル クラスをサポートします。

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] - 実数のコレクションを保存します
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanvector.html[BooleanVector] - ブール値のコレクションを保存します
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexvector.html[ComplexVector] - 複素数のコレクションを保存します

これらのクラスはすべて link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] クラスから派生します。これらは保存するデータ タイプが異なります。

以下のトピックは、Infragistics Math Library でベクトルを使用する方法を説明します。

* link:ig-math-creating-vectors.html[ベクトルの作成]
* link:ig-math-working-with-vectors.html[ベクトルでの作業]

== 関連トピック

link:ig-math-complex-numbers.html[複素数]

link:ig-math-matrices.html[行列]

link:ig-math-mathematical-functions.html[数学関数]