////

|metadata|
{
    "name": "ig-spe-limitations",
    "controlName": ["IG Syntax Parsing Engine"],
    "tags": [],
    "guid": "23094e42-a539-491c-b2f6-b74095116f48",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.1911023Z"
}
|metadata|
////

= 制限 (Syntax Parsing Engine)

== トピックの概要

=== 目的

このトピックは、Syntax Parsing Engine の制限を説明します。

=== 前提条件

このトピックをより理解するために、以下のトピックを参照することをお勧めします。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:ig-spe-overview.html[Syntax Parsing Engine の概要]
|このトピックは、Syntax Parsing Engine の概要を示します。

| link:ig-spe-grammar-overview.html[文書校正の概要]
|このトピックは、Syntax Parsing Engine の文章校正の概要を示します。

| link:ig-spe-lexical-analysis-overview.html[字句解析の概要]
|このグループのトピックでは、Syntax Parsing Engine が行う字句解析について説明します。

| link:ig-spe-syntax-analysis-overview.html[構文解析の概要]
|このグループのトピックでは、Syntax Parsing Engine が行う構文解析について説明します。

|====

=== このトピックの内容

このトピックは、以下のセクションで構成されます。

*  *<<_Ref352339983,記号制限>>*
*  *<<_Ref352339986,生成コード数の制限>>* 
*  *<<_Ref352339990,レクサー状態パスの制限>>* 
*  *<<_Ref352339993,関連コンテンツ>>* 

[[_Ref352339983]]
== 記号制限

=== 概要

パフォーマンスのため、記号はパーサーで一意の整数 ID を割り当てる必要があります。ID は 16 ビットの整数として保存されます。65,536 ID が可能です。ただし、複数の ID は使用できません。従って、許可される終端記号と非終端記号の合計は 65,500 です。

[[_Ref352339986]]
== 生成コード数の制限

生成コードには、一意の 16 ビットの整数 ID が割り当てられます。文章校正で定義されたすべての非終端記号インスタンスの構文ルール ツリーを展開するコードの最大数は 65,536 です。

[[_Ref352339990]]
== レクサー状態パスの制限

Syntax Parsing Engine で実行したレクサー操作は、一致したトークンが状態に入るか、状態から終了するときにスタックに配置されるレクサー状態を使用します。パフォーマンスのため、各スタック構成が 8 ビットの整数 ID に割り当てられます。従って、レクサー状態のスタック構成の最大数は 256 です。

[[_Ref352339993]]
== 関連コンテンツ

=== トピック

このトピックの追加情報については、以下のトピックも合わせてご参照ください。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:ig-spe-restrictions.html[制限]
|このトピックでは、文章校正の定義に関する制限を説明します。

| link:ig-spe-ambiguities.html[あいまいさ]
|このトピックでは、ドキュメントの解析中に発生しうる曖昧さおよびその取扱方法について説明します。

|====