////

|metadata|
{
    "name": "persistence-using-ig-control-persistence-framework",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["Getting Started","How Do I","Persistence"],
    "guid": "{05DBDDDC-77AE-4151-9474-B96D0A20BD3D}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5530369Z"
}
|metadata|
////

= Infragistics Control Persistence Framework の使用

このセクションは、 link:{ApiPlatform}persistence{ApiVersion}~infragistics.persistence_namespace.html[Infragistics Persistence Framework]™ ライブラリが提供する様々な特徴や機能を使用するための重要な概念とタスク ベースの情報について説明します。

== link:persistence-persistence-settings.html[保持の設定]

このトピックでは、PersistenceSettings オブジェクトを使ったコントロール プロパティの保持プロセスの管理について説明します。

== link:persistence-exclude-specific-control-properties.html[特定のコントロールのプロパティを除外]

このトピックでは、Infragistics Control Persistence Framework が実行する保存プロセスから特定のコントロール プロパティを除外する方法について説明します。

== link:persistence-persistence-groups.html[保持グループ]

このトピックでは、PersistenceGroup オブジェクトを作成および使用して、複数のコントロールの設定を、Infragistics Control Persistence Framework が保持することになる 1 つのグループに統合する方法を説明します。

== link:persistence-persisting-specific-control-properties.html[特定のコントロールのプロパティを保持]

このトピックでは、保持する特定のコントロールのプロパティを選択する方法を説明します。

== link:persistence-using-typeconverte.html[PropertyNamePersistenceInfo TypeConverter プロパティの使用]

このトピックでは、PropertyNamePersistenceInfo オブジェクトの TypeConverter プロパティを使用する具体的な事例を説明します。このトピックでは、コード例を使ってプロパティの使用方法を示します。

== link:persistence-handle-persistencesaved-and-persistenceloaded-events.html[PersistenceSaved イベントと PersistenceLoaded イベントの処理]

このトピックでは、PersistenceSaved および PersistenceLoaded イベントを使用して保持プロセスを管理する方法を説明します。

== link:persistence-handle-savepropertypersistence-and-loadpropertypersistence-events.html[SavePropertyPersistence イベントと LoadPropertyPersistence イベントの処理]

このトピックでは、SavePropertyPersistence および LoadPropertyPersistence のイベントを使用して保持プロセスを管理する方法を説明します。