////

|metadata|
{
    "name": "undo-redo-framework",
    "controlName": ["IG Undo Redo Framework"],
    "tags": ["Getting Started"],
    "guid": "3961de75-bd40-45b1-a3c7-e8fcda072341",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.1981018Z"
}
|metadata|
////

= Infragistics Undo/Redo Framework

=== 概要

Infragistics Undo/Redo Framework™ はアプリケーションで元に戻す/やり直し機能を提供します。

フレームワークは操作の履歴を保存し、元に戻す/やり直す操作を実行し、複数の操作を 1 つの履歴項目に結合することが可能です。UI で元に戻す/やり直す操作を実行するには、コマンドを提供します。

このフレームワークはクロスプラットフォームで、WPF または Silverlight アプリケーションのいずれかで使用できます。

=== トピック

Infragistics Undo/Redo Framework についての情報は、以下のトピックで解説します。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:implementing-undo-redo-crud-operations-in-xamgrid-control.html[xamGrid コントロールで CRUD 操作の元に戻す/やり直しを実装]
|このトピックでは、xamGrid™ コントロールで Infragistics Undo/Redo Framework™ を使用する方法を紹介します。このフレームワークが提供する機能を使用して、新しい行の追加、セルの編集および行の削除のようなエンドユーザー操作を元に戻すことができます。

| link:methods-and-properties-reference.html[Undo/Redo Framework メソッドおよびプロパティ参照]
|このセクションには、Infragistics Undo/Redo Framework™ のキー メソッドおよびプロパティに関する参照情報が含まれます。含まれるトピックは、主要なフレームワーク クラスの参照情報、および Undo/Redo API で実行したいタスクに基づいた参照情報を解説します。

|====