////

|metadata|
{
    "name": "wpf-breaking-changes-in-2010-volume-3",
    "controlName": [],
    "tags": ["API","Known Issues"],
    "guid": "7a91714c-b028-4c66-902b-7d884d789e40",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7106953Z"
}
|metadata|
////

= 2010 Volume 3

== xamSchedule

== 既知の問題

[start=1]
. これまでに繰り返しアクティビティが作成される時には、これまでに生成するすべての発生に対してアラームが起動されます。この問題は、今後のリリースで解決されます。
[start=2]
. 関連付けられた繰り返し規則によって生成される最初の発生の開始時間に一致しない開始時間を使用して繰り返しアクティビティが作成されると、繰り返しアクティビティはその開始時間に対して発生を生成しなくなります (生成すべきですが)。組み込みの [予定] ダイアログによって繰り返しアクティビティが作成されると、ルート アクティビティの開始時間は強制的に繰り返し規則によって生成される最初の発生の開始時間になります。これによって、この問題はその事例に当てはまらなくなります。この問題は、今後のリリースで解決されます。
[start=3]
. WcfListConnectorService 派生サービスのひとつを使用する時、項目ソースで提供されるアクティビティ データ項目が通常のビュー オブジェクトである場合 (ActivityBase から作成される)、Reminder プロパティまたは Recurrence プロパティにはプロパティのマッピングを指定できません。そうでないとエラーが発生します。この問題は、今後のリリースで解決されます。
[start=4]
. Xbap アプリケーションでアクティビティをドラッグすると、カーソルは「移動」または「コピー」カーソルに変わりません。この問題は、今後のリリースで解決されます。

== 制限

[start=1]
. ScheduleDialogFactoryBase からクラスを作成し、カスタム ダイアログのコンテンツを表す要素を返すために 'Create…' メソッドを実装する時、Silverlight でコンパイル時に *Infragistics.Controls.Interactions.XamDialogWindow* または *System.Windows.Controls.ChildWindow* のインスタンスを返すべきではありません。こうすると予測不可能な結果が発生する場合があります。この問題は、今後のリリースで削除されます。
[start=2]
. WcfListConnectorService 派生のサービスのひとつを使用して WCF サーバーでプロパティのマッピングを定義すると、メタデータ プロパティのマッピングは無視され、そのデータはクライアントに送られません。クライアントの UI によって項目が追加または更新されると、クライアントからサーバーにメタデータも返されません。この問題は、今後のリリースで削除されます。