////

|metadata|
{
    "name": "xamcomboeditor",
    "controlName": ["xamComboEditor"],
    "tags": ["Getting Started"],
    "guid": "{D256DCE8-E0AF-4A76-B4E1-56D37BAF45DA}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.0639781Z"
}
|metadata|
////

= xamComboEditor

xamComboEditor™ コントロールに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このページをご覧ください。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamComboEditor についての有益な情報を含んでいます。

以下のリンクをクリックして、xamComboEditor コントロールについての情報にアクセスします。

== link:wpf-xamcomboeditor-about-xamcomboeditor.html[xamComboEditor について]

このセクションには xamComboEditor コントロールの機能をより理解するための情報があります。なぜアプリケーションのビルドの一部として使用するかも説明します。

== link:wpf-xamcomboeditor-using-xamcomboeditor.html[xamComboEditor の使用]

このセクションには、xamComboEditor コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:wpf-xamcomboeditor-api-overview.html[API の概要]

このトピックは、xamComboEditor コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックにリストされる名前空間とクラスは、{ProductName} ヘルプの link:api-reference-guide.html[API リファレンス ガイド]に便宜上リンクします。