////
|metadata|
{
    "name": "xamcomboeditor-working-with-the-isalwaysineditmode-property-and-the-editors",
    "tags": ["How Do I"],
    "controlName": ["xamComboEditor"],
    "guid": "0a09c6dc-a850-47e2-a10e-d41c5da7395f",
    "buildFlags": [],
    "createdOn": "2015-09-24T13:16:27.3651937Z"
}
|metadata|
////

= IsAlwaysInEditMode プロパティとエディターによる作業 (xamComboEditor)

{ProductName} エディターの link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~isalwaysineditmode.html[IsAlwaysInEditMode] プロパティはデフォルトで True です。ただし、このエディターがもうひとつのコントロール (xamDataGrid、xamDataCarousel、xamDataPresenter の ValuePresenter) に埋め込まれる時に IsAlwaysInEditMode プロパティは無視されます。したがって、コントロールがロードされる時に、エディターが編集モードになって、フォーカスを失う時でも編集モードのまま変わりません。

IsAlwaysInEditMode プロパティが False に設定されている、またはエディターがもうひとつのコントロール内にホストされる場合には、フォーカスを受け取ると編集モードになり、フォーカスを失うと編集モードを終了します。このルールの例外は、エディターに無効な値が含まれており、 link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~invalidvaluebehavior.html[InvalidValueBehavior] プロパティが RetainValue に設定されている時です。この場合、エディターは編集モードの間に無効な値を持つことができないため、エディターは編集モードのまま変わりません。これに加えて、IsAlwaysInEditMode が False に設定されると、以下の 4 つのイベントが発生します。

* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodestarting_ev.html[EditModeStarting]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodestarted_ev.html[EditModeStarted]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodeending_ev.html[EditModeEnding]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodeended_ev.html[EditModeEnded]