////

|metadata|
{
    "name": "xamcontextmenu",
    "controlName": ["xamContextMenu"],
    "tags": ["Getting Started"],
    "guid": "{43AEEEA6-96CC-4E00-B816-5DAF1805C825}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.776106Z"
}
|metadata|
////

= xamContextMenu

このセクションでは、xamContextMenu™ の使用に関する概要を説明します。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamContextMenu についての有益な情報を含んでいます。以下のリンクをクリックして、xamContextMenu コントロールについての情報にアクセスします。

== link:xamcontextmenu-about-xamcontextmenu.html[xamContextMenu について]

このセクションの説明を読むと、xamContextMenu コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

== link:xamcontextmenu-getting-started-with-xamcontextmenu.html[xamContextMenu をページに追加]

xamContextMenu コントロールを使ってすばやく起動して実行するためのコントロールの使用方法を提供します。

== link:xamcontextmenu-using-xamcontextmenu.html[xamContextMenu の使用]

このセクションには、xamContextMenu コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamcontextmenu-api-overview.html[API の概要]

このトピックは、xamContextMenu コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックに挙げられている名前空間とクラスは、{ProductName} ヘルプの「API リファレンス ガイド」セクションにリンクされています。