////

|metadata|
{
    "name": "xamdatapresenter-navigating-and-selecting",
    "controlName": ["xamDataPresenter"],
    "tags": ["Navigation","Selection"],
    "guid": "{2A36B111-672C-4CC3-90DC-CAE453F98B2E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2710073Z"
}
|metadata|
////

= ナビゲーションと選択



キーボードとマウスは、どこにでもあるパーソナル コンピューターの標準的な周辺機器です。これらの周辺機器をすぐに使用することがすべてのエンドユーザーのコンピューター エクスペリエンスにとって鍵となります。キーボードの特定のキーを使用してエンドユーザーがグリッドのデータ、ツリーのノード、リストの項目をナビゲートすることを可能にすることによって、そのエクスペリエンスを利用することができます。ユーザーがマウス ボタンをクリックする、またはマウス ホイールをスクロールする時に選択される項目を制御することさえできます。

xamDataPresenter™ コントロールのオブジェクト モデルには、エンドユーザーが希望する場合にはキーボードで完全にナビゲートすることを可能にするために必要なツールが含まれています。マウス イベントの処理も xamDataPresenter の標準的な機能です。これによってエンドユーザーは馴染みのあるポイント アンド クリック エクスペリエンスを提供します。

xamDataPresenter コントロールを使用してナビゲーションと選択を実装することに特化したトピックをご覧になるには、以下のリンクをクリックしてください。

* link:xamdata-selection-overview.html[選択の概要]
* link:xamdata-accessing-records-through-the-recordmanager.html[RecordManager によってレコードにアクセス]
* link:xamdata-changing-field-record-cell-selection-behavior.html[フィールド、レコード、またはセル選択の動作を変更]
* link:xamdatapresenter-keyboard-navigation-in-xamdatapresenter.html[xamDataPresenter でのキーボード ナビゲーション]
* link:xamdatapresenter-configuring-custom-tab-navigation.html[カスタム タブのナビゲーションの構成]
* link:xamdata-using-data-presenter-family-commands.html[Data Presenter Family コマンドの使用]
* link:xamdatapresenter-selected-data-items.html[選択済みのデータ項目]