////
|metadata|
{
    "name": "xamdatapresenter-exporting-data-to-word",
    "controlName": ["xamDataPresenter"],
    "tags": ["Exporting","Grids","How Do I"],
    "guid": "372bdabc-58c0-4e3c-b158-7cfcc0d24300",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.3810293Z"
}
|metadata|
////

= xamDataPresenter を使用してデータを Word にエクスポート

このトピックでは、xamDataPresenter コントロールを使用して、Word へのデータの エクスポートを実装する方法を説明します。

== はじめに

DataPresenter コントロールは、DataPresenterExcelExporter クラスを使用して、Microsoft® Word® フォーマットでデータをエクスポートできます。link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter.html[DataPresenterWordWriter] クラスは、特定の DataPresenterBase の値/レイアウトを表すテーブルを含む Word 文書を作成するすべての作業をカプセル化します。

DataPresenterWordWriter クラスはビジュアル要素ではありません。このため、ウィンドウのビジュアル ツリーに追加できません。ただし、XAML で DataPresenterWordWriter オブジェクトのインスタンスを作成したい場合には、ウィンドウのリソースディクショナリに追加できます。

.注:
[NOTE]
====
DataPresenter コントロールのスタイルの柔軟性のために、DataPresenterWordWriter オブジェクトは DataPresenter コントロールのスタイルを Word にエクスポートしません。ただし、インフラジスティックスの Word Engine オブジェクトに直接アクセスする、またはエクスポートの前にフォーマットを適用することによって、結果のドキュメントを書式設定できます。
====

== 要件

データをエクスポートできるようにするには、以下の NuGet パッケージを参照する必要があります。

* Infragistics.WPF.DataGrids
* Infragistics.WPF.DataGrids.Word

NuGet フィードのセットアップと NuGet パッケージの追加の詳細については、link:nuget-feeds.html[NuGet フィード] ドキュメントを参照してください。

== 概要

エクスポート手順の概念的な概要

[start=1]
. グリッドを追加
[start=2]
. エクスポート ボタンを追加
[start=3]
. xamDataPresenter コントロールを追加
[start=4]
. コード ビハインドに using/imports のディレクティブを追加
[start=5]
. (条件付き) Button の Click イベントのイベント ハンドラーを追加
[start=6]
. DataPresenterWordWriter オブジェクトのインスタンスを作成
[start=7]
. エクスポート メソッドを呼び出す
[start=8]
. (条件付き) 実装を検証

== 手順

[start=1]
. *グリッドを追加します。*

2 つの RowDefinition オブジェクトがある Grid パネルをウィンドウに追加します。

*XAML の場合:*

[source,xaml]
----
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition />
    </Grid.RowDefinitions>
    <!--TODO: Button コントロールを追加します-->
    <!--TODO: xamDataPresenter コントロールを追加します-->
</Grid>
----

[start=2]
. *エクスポート ボタンを追加します。*

Button コントロールを Grid パネルの最初の行に追加します。

** Content プロパティを "Export DataPresenter" に設定します。
** イベント ハンドラーを Click イベントに添付します。

*XAML の場合:*

[source,xaml]
----
<Button Content="Export DataPresenter" Click="Button_Click" />
----

[start=3]
. *xamDataPresenter コントロールを追加します。*

xamDataPresenter コントロールを Grid パネルの 2 番目の行に追加します。

** Name プロパティを xamDataPresenter1 に設定します。
** link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~bindtosampledata.html[BindToSampleData] プロパティを True に設定します。

*XAML の場合:*

[source,xaml]
----
<igDP:XamDataPresenter Name="xamDataPresenter1" BindToSampleData="True">
</igDP:XamDataPresenter>
----

[start=4]
. *コード ビハインドに using/imports のディレクティブを追加します。*

コード ビハインドを開き、コード ビハインド内に using/Imports のディレクティブを配置すれば、メンバーの完全に記述された名前を常にタイプする必要がなくなります。コードでインスタンスを作成する代わりに、DataPresenterWordWriter オブジェクトのインスタンスをウィンドウのリソース ディクショナリに追加したい場合には、XML 名前空間宣言を追加することが必要になります。

*XAML の場合:*

[source,xaml]
----
xmlns:igWordWriter="http://infragistics.com/WordWriter"
----

*Visual Basic の場合:*

[source,vb]
----
imports Infragistics.Windows.DataPresenter.WordWriter
----

*C# の場合:*

[source,csharp]
----
using Infragistics.Windows.DataPresenter.WordWriter;
----

[start=5]
. (条件付き) Button の Click イベントのイベント ハンドラーを追加します。

メソッド スタブが作成されていない場合には、Button コントロールの Click イベントのイベント ハンドラーを追加することが必要になります。

*Visual Basic の場合:*

[source,vb]
----
Private Sub Button_Click(sender As Object, e As RoutedEventArgs)
    'TODO: DataPresenterWordWriter オブジェクトのインスタンスを作成します
    'TODO: DataPresenterWordWriter オブジェクトの Export メソッドを呼び出します
End Sub
----

*C# の場合:*

[source,csharp]
----
private void Button_Click(object sender, RoutedEventArgs e)
{
    //TODO: DataPresenterWordWriter オブジェクトのインスタンスを作成します
    //TODO: DataPresenterWordWriter オブジェクトの Export メソッドを呼び出します
}
----

[start=6]
. *DataPresenterWordWriter オブジェクトのインスタンスを作成します。*

XAML でインスタンスを作成している場合には、ウィンドウのリソース ディクショナリに追加できます。

*XAML の場合:*

[source,xaml]
----
<Window.Resources>
    <igWordWriter:DataPresenterWordWriter x:Key="wordWriter1" />
</Window.Resources>
----

*Visual Basic の場合:*

[source,vb]
----
Dim writer As New DataPresenterWordWriter()
' DataPresenterWordWriter オブジェクトを
' ウィンドウのリソース ディクショナリに追加した場合には、コードのこの行を使用します
' Dim writer As DataPresenterWordWriter =
' DirectCast(Me.Resources("wordWriter1"), DataPresenterWordWriter)
----

*C# の場合:*

[source,csharp]
----
DataPresenterWordWriter writer = new DataPresenterWordWriter();
// DataPresenterWordWriter オブジェクトを
// ウィンドウのリソース ディクショナリに追加した場合には、コードのこの行を使用します
// DataPresenterWordWriter writer =
// (DataPresenterWordWriter)this.Resources["wordWriter1"];
----

[start=7]
. *エクスポート メソッドを呼び出します。*

データを同期でエクスポートするか、非同期でエクスポートするかによって、 link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter~export.html[Export] と link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter~exportasync.html[ExportAsync] の 2 つのメソッドを選択できます。

データを同期でエクスポートするには:

DataPresenterWordWriter オブジェクトの Export メソッドを呼び出します。

*Visual Basic の場合:*

[source,vb]
----
writer.Export(Me.xamDataPresenter1, "xamDataPresenter1.docx")
----

*C# の場合:*

[source,csharp]
----
writer.Export(this.xamDataPresenter1, "xamDataPresenter1.docx");
----

データを非同期でエクスポートするには:

DataPresenterWordWriter オブジェクトの ExportAsync を呼び出してデータを非同期でエクスポートします。

*Visual Basic の場合:*

[source,vb]
----
writer.ExportAsync(Me.xamDataPresenter1, "xamDataPresenter1.docx")
----

*C# の場合:*

[source,csharp]
----
writer.ExportAsync(this.xamDataPresenter1, "xamDataPresenter1.docx");
----

.非同期エクスポートの注意事項:
[NOTE]
====
. 非同期エクスポートはデータをチャンクでエクスポートします。各チャンクは、 link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter~asyncexportduration.html[AsyncExportDuration] プロパティによって指定された時間、処理され、2 つのチャンク処理間の時間は link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter~asyncexportinterval.html[AsyncExportInterval] プロパティで指定されます。
. ExportAsync メソッドを呼び出し、エクスポート処理が終了した時を追跡したい場合には、 link:{ApiPlatform}datapresenter.wordwriter{ApiVersion}~infragistics.windows.datapresenter.wordwriter.datapresenterwordwriter~exportended_ev.html[ExportEnded] イベントをフックするのが賢明です。
====

[start=8]
. (条件付き) 実装を検証します。

プロジェクトを実行して、エクスポート ボタンをクリックします。これによって xamDataPresenter コントロールが Word にエクスポートされます。

== 関連トピック

link:xamdatapresenter-applying-formats-when-exporting-data.html[データをエクスポートする時にフォーマットを適用]

link:xamdatapresenter-exclude-settings.html[エクスポート時の DataPresenter の Exclude 設定]

link:xamdatapresenter-exporting-to-word-events.html[エクスポート イベントを処理することでエクスポートを管理]