////
|metadata|
{
    "name": "xamdatapresenter-accessing-data",
    "controlName": ["xamDataPresenter"],
    "tags": ["Data Binding","How Do I"],
    "guid": "{C01A2A42-36FC-4849-86E6-6E0213782580}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.0749681Z"
}
|metadata|
////

= xamDataPresenter をデータにバインド



データ バインディングは、xamDataPresenter™、xamDataGrid™、xamDataCarousel™ および xamDataCards™ をはじめとするあらゆるデータ プレゼンテーション コントロールで極めて重要な役割を果たします。xamDataCards コントロールが表示できるのはフラットなデータのみですが、その他のコントロールはフラットなデータに加えて階層的なデータを表示できます。

デフォルトで、上記のコントロールのいずれをバインドする時にも、データ ソースで一意のタイプのオブジェクトごとに FieldLayout を作成します。データ項目内の公的に公開されたプロパティはそれぞれ、FieldLayout に対応する Field があります。IEnumerable インターフェイスを実装するオブジェクトを公的に公開されたプロパティが返し、コントロールが階層データをサポートする場合、コントロールは展開インジケーターを表示します。これによってエンドユーザーは階層をドリルダウンできます。

== データ バインディングの要件

Microsoft® Windows® Presentation Foundation のデータ バインドされたコントロールと全く同じように、データ プレゼンテーション コントロールにデータをバインドするために満たさなければならないいくつかの要件があります。

* オブジェクトは IEnumerable インターフェイス (たとえば ObservableCollection<T>, ArrayList、DataView など) を実装する必要があります。
* DataSourceProvider クラス (たとえば、XmlDataProvider、ObjectDataProvider または固有のカスタム データ プロバイダー) から派生するオブジェクトを使用している場合、データ プロバイダーの Data プロパティは IEnumerable インターフェイスを実装するオブジェクトを返さなければなりません。

* link:xamdatapresenter-bind-a-datapresenter-control-to-an-xmldataprovider.html[DataPresenter コントロールを XmlDataProvider にバインド]
* link:xamdatapresenter-bind-a-datapresenter-control-to-a-collection.html[DataPresenter コントロールをコレクションにバインド]
* link:xamdatapresenter-binding-a-datapresenter-control-to-a-dataset.html[DataPresenter コントロールを DataSet にバインド]
* link:xamdatapresenter-binding-field-fieldlayout-to-mvvm.html[Field、FieldSettings、FieldLayout および FieldLayoutSettings の MVVM プロパティへのバインド]
* link:xamdatapresenter-binding-cell-settings-data-item-properties.html[セル設定のデータ項目プロパティへのバインド]
* link:xamdatapresenter-about-data-items-and-data-records.html[データ項目とデータ レコードについて]
* link:xamdatapresenter-add-items-manually-to-a-datapresenter-control.html[項目を手動で DataPresenter コントロールに追加]
* link:xamdata-displaying-hierarchical-data.html[階層データを表示]
* link:xamdatapresenter-displaying-an-image-in-a-field.html[フィールドに画像を表示]
* link:xamdatapresenter-iterate-through-the-records-collection.html[レコード コレクションで繰り返し]
* link:xamdatapresenter-asynchronouspagingdatasource.html[非同期ページングのデータ ソース (xamDataPresenter)]