////

|metadata|
{
    "name": "xamdatapresenter-disable-sorting",
    "controlName": ["xamDataPresenter"],
    "tags": ["How Do I","Sorting"],
    "guid": "{2EA23AE3-4522-439F-A556-029D18034FCB}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1479827Z"
}
|metadata|
////

= 並べ替えを無効にする



エンド ユーザーが link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[フィールド] のヘッダーをクリックすると、xamDataPresenter グリッドビューはデータを並べ替えます。グリッド ビューでエンド ユーザーがデータをソートできなくするには、 link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~labelclickaction.html[FieldSettings] の link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings.html[LabelClickAction] プロパティを設定します。

以下の手順は、データ バインドされた xamDataPresenter があり、そこで並べ替えを無効にすることを想定しています。詳細については、 link:xamdatapresenter-getting-started-with-xamdatapresenter.html[xamDataPresenter をアプリケーションに追加]を参照してください。

[start=1]
. xamDataPresenter のインスタンスを作成し名前を指定します。FieldSettings オブジェクトを指定し、そこから LabelClickAction を Nothing に設定できます。

*XAML の場合:*

----
<igDP:XamDataPresenter x:Name="XamDataPresenter1" 
  ...
>
    <igDP:XamDataPresenter.View>
        <igDP:GridView/>
    </igDP:XamDataPresenter.View>
    <igDP:XamDataPresenter.FieldSettings>
        <igDP:FieldSettings LabelClickAction="Nothing" />
    </igDP:XamDataPresenter.FieldSettings>
</igDP:XamDataPresenter>
----

[start=2]
. プロジェクトをビルドして実行します。Field のヘッダーをクリックしたときにグリッド ビューは並べ替えません。

== 関連トピック

link:xamdatapresenter-about-sorting.html[並べ替えについて]

link:xamdatapresenter-sorting-and-grouping-fields-programmatically.html[フィールドのプログラムによる並べ替えおよびグループ化]