////

|metadata|
{
    "name": "xamdockmanager-about-opening-and-closing-panes",
    "controlName": ["xamDockManager"],
    "tags": ["Getting Started"],
    "guid": "{E867A904-69D6-4EB6-91CD-989515D4808F}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.4790489Z"
}
|metadata|
////

= 開始ペインと終了ペインについて

xamDockManager™ コントロールによって、エンド ユーザーはペインを閉じたり表示から隠すことができます。ただし、ピンニングとアンピンニング ペインと異なり、閉じたペインを開くための機能を実装しない限り、閉じたペインをエンド ユーザーが表示する方法はありません。

エンド ユーザーがペインを閉じると、デフォルトで非表示となります。デフォルトでは、閉じたペインを開くには、コンテンツのペインの link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.contentpane.html[Visibility] プロパティを Visible に設定する必要があります。ただし、コンテンツペインの link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.contentpane~closeaction.html[CloseAction] プロパティを明示的に RemovePane に設定すると、xamDockManager はドッキング レイアウトからコンテンツ ペインを削除します。削除されたペインを開くには、それを適切な分割ペインの link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.splitpane~panes.html[Panes コレクション]またはタブ グループ ペインの link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.tabgrouppane.html[Items コレクション]に再追加する必要があります。

== 関連トピック

link:xamdockmanager-add-content-to-a-contentpane.html[コンテンツを ContentPane に追加]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[ペインを DocumentContentHost オブジェクトに追加]

link:xamdockmanager-add-panes-to-xamdockmanager.html[ペインを xamDockManager に追加]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[タブ付き MDI アプリケーションを作成]

link:xamdockmanager-pin-and-unpin-a-pane.html[ペインのピンを固定および解除]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[エンドユーザーがフローティング ペインのサイズを変更することを禁止]

link:xamdockmanager-set-the-location-of-a-floating-pane.html[フローティング ペインの場所を設定]

link:xamdockmanager-set-the-initial-location-of-a-pane.html[ペインの最初の位置を設定]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[フローティング ペインのサイズを設定]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[プログラミングによるペイン ナビゲータの表示]

link:xamdockmanager-end-user-settings.html[エンドユーザー設定]

link:xamdockmanager-styling-xamdockmanager.html[xamDockManager のスタイリング]