////

|metadata|
{
    "name": "xamdockmanager-set-the-location-of-a-floating-pane",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I"],
    "guid": "{FB0109AE-167A-4D15-95F0-8A3974A6E30E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5270585Z"
}
|metadata|
////

= フローティング ペインの場所を設定



xamDockManager™ コントロールの link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~initiallocationproperty.html[InitialLocation] 添付プロパティを FloatingOnly に設定することでペインをフロートする場合、xamDockManager の link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~floatinglocationproperty.html[FloatingLocation] 添付プロパティを Point 構造のインスタンスに設定することでフローティング ペインを配置できます。XAML では、コンマまたはスペースで分割された x 座標および y 座標を指定することで FloatingLocation 添付プロパティを設定できます。

以下のコードは、フローティング ペインの場所を設定する方法を示します。

*XAML の場合:*

----
...
<igDock:XamDockManager Name="xamDockManager1">
    <igDock:XamDockManager.Panes>
        <igDock:SplitPane 
            Name="splitPane1" 
            igDock:XamDockManager.FloatingLocation="0 0"
            igDock:XamDockManager.InitialLocation="FloatingOnly">
            <igDock:ContentPane Header="Pane 1">
                <!--TODO: ここでコンテンツを追加します-->
            </igDock:ContentPane>
        </igDock:SplitPane>
    </igDock:XamDockManager.Panes>
</igDock:XamDockManager>
...
----

*Visual Basic の場合:*

----
Imports Infragistics.Windows.DockManager
...
Dim splitPane1 As New SplitPane() 
XamDockManager.SetFloatingLocation(splitPane1, New Point(0, 0)) 
XamDockManager.SetInitialLocation(splitPane1, InitialPaneLocation.FloatingOnly) 
Me.xamDockManager1.Panes.Add(splitPane1) 
Dim pane1 As New ContentPane() 
pane1.Header = "Pane 1" 
splitPane1.Panes.Add(pane1) 
...
----

*C# の場合:*

----
using Infragistics.Windows.DockManager;
...
SplitPane splitPane1 = new SplitPane();
XamDockManager.SetFloatingLocation(splitPane1, new Point(0, 0));
XamDockManager.SetInitialLocation(splitPane1, InitialPaneLocation.FloatingOnly);
this.xamDockManager1.Panes.Add(splitPane1);
ContentPane pane1 = new ContentPane();
pane1.Header = "Pane 1";
splitPane1.Panes.Add(pane1);
...
----

== 関連トピック

link:xamdockmanager-about-opening-and-closing-panes.html[開始ペインと終了ペインについて]

link:xamdockmanager-add-content-to-a-contentpane.html[コンテンツを ContentPane に追加]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[ペインを DocumentContentHost オブジェクトに追加]

link:xamdockmanager-add-panes-to-xamdockmanager.html[ペインを xamDockManager に追加]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[タブ付き MDI アプリケーションを作成]

link:xamdockmanager-pin-and-unpin-a-pane.html[ペインのピンを固定および解除]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[エンドユーザーがフローティング ペインのサイズを変更することを禁止]

link:xamdockmanager-set-the-initial-location-of-a-pane.html[ペインの最初の位置を設定]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[フローティング ペインのサイズを設定]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[プログラミングによるペインナビゲータの表示]

link:xamdockmanager-end-user-settings.html[エンドユーザー設定]

link:xamdockmanager-styling-xamdockmanager.html[xamDockManager のスタイリング]