////

|metadata|
{
    "name": "xamdatatree-xamdatatree-editing",
    "controlName": ["xamDataTree"],
    "tags": ["Editing","Events"],
    "guid": "0e61075c-c85e-4f74-bf47-4d32b34988fa",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9051125Z"
}
|metadata|
////

= xamDataTree 編集

xamDataTree コントロールでは、各行でデータを編集することが可能です。xamDataTree コントロールの編集を有効にするには、 link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.nodelayout~editingsettings.html[TreeEditingSettings] のオブジェクトの link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettings~allowediting.html[AllowEditing] プロパティを True に設定します。link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettingsoverride.html[TreeEditingSettingsOverride] オブジェクトのプロパティを設定することによって、異なるノード レベルで編集を有効または無効にすることもできます。TreeEditingSettingsOverride オブジェクトは、TreeEditingSettings オブジェクトに優先します。

以下のコードは、xamDataTree で編集を有効にする方法および Products レベルで無効にする方法を示しています。

*XAML の場合:*

----
<ig:XamDataTree x:Name="MyTree">
   <ig:XamDataTree.EditingSettings>
      <ig:TreeEditingSettings AllowEditing="True"/> 
   </ig:XamDataTree.EditingSettings>
   <ig:XamDataTree.GlobalNodeLayouts>
      <ig:NodeLayout Key="CategoryLayout" TargetTypeName="Category" 
                     DisplayMemberPath="CategoryName"/>
      <ig:NodeLayout Key="ProductLayout" TargetTypeName="Product" 
                     DisplayMemberPath="ProductName">
         <ig:NodeLayout.EditingSettings>
            <ig:TreeEditingSettingsOverride AllowEditing="False"/>
         </ig:NodeLayout.EditingSettings>
      </ig:NodeLayout>
   </ig:XamDataTree.GlobalNodeLayouts>
</ig:XamDataTree>
----

*Visual Basic の場合:*

----
MyTree.EditingSettings.AllowEditing = True
MyTree.GlobalNodeLayouts(1).EditingSettings.AllowEditing = False
----

*C# の場合:*

----
MyTree.EditingSettings.AllowEditing = true;
MyTree.GlobalNodeLayouts[1].EditingSettings.AllowEditing = false;
----

編集モードを開始するにはいくつかの異なる方法があります。以下の TreeEditingSettings および TreeEditingSettingsOverride オブジェクト プロパティを設定することで決定できます。

link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettingsoverride~isf2editingenabled.html[IsF2EditingEnabled] - このプロパティは、F2 キーを押した時にノードが編集モードになるかどうかを指定します。

link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettings~isenterkeyeditingenabled.html[IsEnterKeyEditingEnabled] - このプロパティは、Enter キーを押した時にノードが編集モードになるかどうかを指定します。

link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettings~isonnodeactiveeditingenabled.html[IsOnNodeActiveEditingEnabled] - このプロパティは、ノードが自動的に編集モードになるかどうかを指定します。

link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettings~ismouseactioneditingenabled.html[IsMouseActionEditingEnabled] - このプロパティは、以下の link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treemouseeditingaction.html[TreeMouseEditingAction] 列挙値のいずれかに設定する必要があります。

* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treemouseeditingaction.html[DoubleClick] - この値は、ダブルクリックした時にノードが編集モードになるかどうかを指定します。
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treemouseeditingaction.html[SingleClick] - この値は、クリックした時にノードが編集モードになるかどうかを指定します。
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treemouseeditingaction.html[None] - この値はノードをクリックした時に編集モードにならないように指定します。

[NOTE]
====
*注:* Esc キーを押すと編集モードをキャンセルできます。ENTER キーを押すか、エディター領域の外側でマウスをクリックすると、編集された値が確定されます。
====

*イベント*

以下のリストに示すように、xamDataTree に関連づけられたイベントが 4 つあります。これらのイベントによって、編集中にカスタム ロジックを実行できます。

[NOTE]
====
*注:* NodeEnteringEditMode などの "ing" イベントはすべてキャンセル可能です。
====

* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatree~nodeenteringeditmode_ev.html[NodeEnteringEditMode]
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatree~nodeenterededitmode_ev.html[NodeEnteredEditMode]
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatree~nodeexitingeditmode_ev.html[NodeExitingEditMode]
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatree~nodeexitededitmode_ev.html[NodeExitedEditMode]
* link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatree~nodeeditingvalidationfailed_ev.html[NodeEditingValidationFailed]

*エディター テンプレート*

TextBox は編集モードになっているノード用のデフォルト エディターで、XamDataTree または link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.nodelayout~nodelayouts.html[NodeLayouts] オブジェクトの link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.nodelayout~displaymemberpath.html[DisplayMemberPath] プロパティで設定された値を編集することしかできません。ノードから離れたところをクリックすると、更新されます。

ただし、編集のためにユーザー独自のテンプレートを設定することもできます。これは XamDataTree または NodeLayouts オブジェクトの link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.nodelayout~editortemplate.html[EditorTemplate] プロパティをデータ テンプレートのインスタンスに設定することで実行可能です。DataTemplate で指定されたこのカスタム エディターの DataContext は link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.xamdatatreenodedatacontext.html[XamDataTreeNodeDataContext] です。このカスタム テンプレートを実装すれば、項目で複数値を編集できます。

編集される値にバインドされると、編集をキャンセルできるようにするために、Binding オブジェクトで UpdateSourceTrigger プロパティを Explicit に設定する必要があります。

次のコードは、このような動作の実行方法を示します。

*XAML の場合:*

----
<ig:NodeLayout Key="ChapterLayout" TargetTypeName="Book" DisplayMemberPath="Title">
   <ig:NodeLayout.EditorTemplate>
      <DataTemplate>
         <Grid>
            <Grid.RowDefinitions>
               <RowDefinition></RowDefinition>
               <RowDefinition></RowDefinition>
            </Grid.RowDefinitions>
            <TextBox Background="Red" Grid.Row="0" Text="{Binding Data.Title, Mode=TwoWay,UpdateSourceTrigger=Explicit}"></TextBox>
            <TextBox Background="Yellow" Grid.Row="1" Text="{Binding Data.Author, Mode=TwoWay,UpdateSourceTrigger=Explicit}"></TextBox>
         </Grid>
      </DataTemplate>
   </ig:NodeLayout.EditorTemplate>
</ig:NodeLayout>
----

*ノードの削除*

xamDataTree コントロールからノードを削除することもできます。次のコードで示すように、TreeEditingSettings オブジェクトの link:{ApiPlatform}controls.menus.xamdatatree{ApiVersion}~infragistics.controls.menus.treeeditingsettings~allowdeletion.html[AllowDeletion] プロパティを設定することで、ノードを削除することを可能にします。削除が有効になったら、DELETE キーを使用してノードを削除できます。

*XAML の場合:*

----
<ig:XamDataTree.EditingSettings>
   <ig:TreeEditingSettings AllowEditing="True" 
                           AllowDeletion="True"/> 
</ig:XamDataTree.EditingSettings>
----

*Visual Basic の場合:*

----
MyTree.EditingSettings.AllowDeletion = True
----

*C# の場合:*

----
MyTree.EditingSettings.AllowDeletion = true;
----

*関連トピック*

link:xamdatatree-xamdatatree-activation.html[アクティブ化]

link:xamdatatree-active-data-item.html[アクティブなデータ アイテムの構成]

link:xamdatatree-xamdatatree-check-boxes.html[チェックボックスの表示状態の構成]

link:xamdatatree-expanded-and-collapsed-xamdatatree-nodes.html[ノードの展開と縮小の構成]

link:xamdatatree-xamdatatree-drag-and-drop.html[ドラッグ アンド ドロップの構成]

link:xamdatatree-xamdatatree-node-connectors.html[ノード コネクターの表示状態の構成]

link:xamdatatree-xamdatatree-node-layouts.html[ノード レイアウトの構成]

link:xamdatatree-xamdatatree-selection.html[選択]