////

|metadata|
{
    "name": "xamdialogwindow-using-xamdialogwindow",
    "controlName": ["xamDialogWindow"],
    "tags": [],
    "guid": "{D945D272-BE03-447F-8062-D9F7F12A1EBD}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9521229Z"
}
|metadata|
////

= xamDialogWindow の使用

このセクションでは、xamDialogWindow™ コントロールの様々な機能を使用するために役立つ、重要な概念やタスク ベースの情報について説明します。

link:xamdialogwindow-custom-cursors.html[カスタム カーソル]

このトピックでは、DataTemplates を使用して xamDialogWindow コントロールのサイズ変更カーソルをカスタマイズする方法について説明します。

link:xamdialogwindow-customize-modal-dialog-window-background.html[モーダル ダイアログ ウィンドウの背景のカスタマイズ]

このトピックでは、モーダル xamDialogWindow コントロールの背景にエフェクトを適用する方法について説明します。

link:xamdialogwindow-customize-the-window-header-icon.html[ウィンドウ ヘッダー アイコンのカスタマイズ]

このトピックでは、コントロールのヘッダー アイコンを変更する方法について説明します。

link:xamdialogwindow-handle-moving-events.html[移動イベントの処理]

このトピックでは、コントロールの Moving および Moved イベントについて説明します。

link:xamdialogwindow-handle-window-state-changing-events.html[ウィンドウ状態変更イベントの処理]

このトピックでは、xamDialogWindow の状態変化に関連したイベントについて説明します。ウィンドウの状態は、通常、最小化、最大化、および非表示の間で切り替わります。

link:xamdialogwindow-keyboard-settings.html[キーボードの設定]

このトピックでは、xamDialogWindow コントロールを矢印キーで移動できるようにキーボード ナビゲーションを有効化して微調節を加える方法について説明します。

link:xamdialogwindow-modal-and-modeless-dialog-windows.html[モーダル/モードレス ダイアログ ウィンドウ]

このトピックでは、モーダルの xamDialogWindow を作成する方法について説明します。

link:xamdialogwindow-position-minimized-dialog-window.html[位置最小化ダイアログ ウィンドウ]

このトピックでは、xamDialogWindow コントロールを最小化してパネルに格納する方法について説明します。

link:xamdialogwindow-set-the-dialog-windows-height-and-width-when-minimized.html[最小化した時のダイアログ ウィンドウの高さと幅を設定]

このトピックでは、xamDialogWindow コントロールの MinimizedWidth および MinimizedHeight プロパティの使用法について説明します。

link:xamdialogwindow-start-up-position-of-xamdialogwindow.html[xamDialogWindow の開始位置]

このトピックでは、xamDialogWindow コントロールの初期位置をセットアップする方法について説明します。

link:xamdialogwindow-the-xamdialogwindow-controls-behavior.html[xamDialogWindow コントロールの動作]

このトピックでは、複数のコンテナーにネストされている xamDialogWindow の動作について説明します。

link:xamdialogwindow-window-header-controls.html[ウィンドウ ヘッダー コントロール]

このトピックでは、xamDialogWindow コントロールの CloseButtonVisibility、MaximizeButtonVisibility、および MinimizeButtonVisibility プロパティの使用法について説明します。