////

|metadata|
{
    "name": "xamdiagram-user-interactions-configuration-overview",
    "tags": ["Charting","Getting Started","How Do I","Summaries"],
    "controlName": ["xamDiagram"],
    "guid": "ab1aeda3-3f6e-4277-a445-f7301aececa6",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:37:15.6243875Z"
}
|metadata|
////

= ユーザー インタラクションの構成の概要 (xamDiagram)

[[_Ref391537902]]
== _xamDiagram_   ユーザー インタラクションの構成の概要

=== 目的

このトピックでは、 _xamDiagram_™ コントロールで実行するユーザー インタラクションのすべてのタスクの概要を説明します。

=== 前提条件

このトピックをより理解するために、以下のトピックを参照することをお勧めします。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xamdiagram-general-overview.html[概要 ( _xamDiagram_ )]
|このトピックでは、 _xamDiagram_ コントロールの概要を説明します。

|====

[[_Ref391538059]]
== ユーザー インタラクションの構成の概要

[[_Ref391538063]]

=== xamDiagram ユーザー インタラクションの構成の概要表

include::xamdiagram-user-interactions-configuration-summary-chart.ja-JP.adoc[]

[[_Ref391538068]]

=== コマンド

_xamDiagram_   コントロールは、ダイアグラム項目で実行されるアクションやコントロールの UI とのインタラクションを表すことができるコマンド セット、元に戻す / やり直し操作の履歴に影響を与えるコマンド セットをサポートします。コマンドは、キーボード ショートカット、その他のコントロールとのインタラクションなどを使用して呼び出すことができます。

多くのコマンドは、一般的なインターフェイスの規格に従って、キーボードのキーやキーの組み合わせに関連付けられています (コピーする場合の Ctrl+Cなど)。ただし、プログラムによるオーバーライドで、キーボード ショートカット (またはキーの組み合わせ) を変更することができます。(詳細は、 link:xamdiagram-configuring-keyboard-shortcuts.html[キーボード ショートカットの構成]を参照してください。)

==== 関連トピック:

* link:xamdiagram-configuring-ui-elements-with-commands.html[ _xamDiagram_  コマンドを使用した UI 要素の構成]

[[_Ref391538072]]

=== コンテキスト メニュー

_xamDiagram_   コントロールのダイアグラムの項目は、コントロールのコンテキスト メニューの機能を使用して構成できます。コンテキスト メニューはオプション ペインで表示することができます。ダイアグラムの項目 (複数可) を選択すると表示されるギア アイコンをクリックすると、オプション ペインが表示されます。デフォルトでは、コンテキスト メニューはダイアグラムで無効になっています。

==== 関連トピック:

* link:xamdiagram-configuring-the-context-menu.html[コンテキスト メニューの構成 ( _xamDiagram_ )]

[[_Ref391538076]]

=== マウス操作とツール

_xamDiagram_   では、マウスによる xamDiagram の複数の操作方法が提供されています。操作は link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] と link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction] の 2 つのプロパティで設定されます。link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] の設定では、 _xamDiagram_   上でクリックとドラッグを実行した場合の状態を設定します。以下のツールを使用できます。

* ポインター
* コネクタ

デフォルトはポインターです。これにより、 link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction] 設定で制御される複数の操作を実行できます。サポートされる操作は以下のとおりです。

* なし
* ズーム
* パン
* 選択  _(デフォルト)_  

コネクタ ツールでは、接続をダイアグラムにドラッグすることで描画できます。

==== 関連トピック:

* link:xamdiagram-configuring-the-mouse-tool-and-default-interaction.html[マウス ツールおよびデフォルト操作の構成 ( _xamDiagram_ )]

[[_Ref391538082]]

=== ナビゲーション ペイン

_xamDiagram_   コントロールには、ダイアグラム スペース内 (デフォルトは右下隅) に配置された別のペインに、コンテンツ タイプ全体の概要を小さなサイズで表示できる機能があります。

==== 関連トピック:

* link:xamdiagram-configuring-the-navigation-pane.html[ナビゲーション ペインの構成 ( _xamDiagram_ )]

[[_Ref391538088]]

=== 選択

_xamDiagram_   コントロールでは、ダイアグラム領域にあるダイアグラムの項目をコードおよびユーザー操作によって選択できるようにする機能が提供されています。使用できる選択機能には、「Single」、「Multiple」、「None」があり、いずれもプロパティの設定で構成できます。デフォルトでは、ダイアグラムの複数の項目の選択が有効になっています。

==== 関連トピック:

* link:xamdiagram-configuring-selection.html[選択の構成 ( _xamDiagram_ )]

[[_Ref391538095]]

=== キーボード ショートカット

_xamDiagram_   は、コマンドに関連付けられたキーボード ショートカットのセットを公開します。すべてのショートカットのリストについては、 link:xamdiagram-general-overview.html[概要]を参照してください。定義済みのショートカットの変更、または削除して新しいショートカットを定義することができます。

==== 関連トピック:

* link:xamdiagram-configuring-keyboard-shortcuts.html[キーボード ショートカットの構成 ( _xamDiagram_ )]

[[_Ref391538100]]

=== ツールボックス

_xamDiagram_   コントロールでは、定義済みの図形セットから直接ダイアグラムにダイアグラム項目をドラッグ アンド ドロップできる機能が提供されています。この機能は、 _xamDiagramToolbox_™ コントロールにより提供されます。デフォルトでは、2 つの事前構成済みの図形カテゴリ (ラベルを表すノードなど、現在サポートされているすべてのダイアグラム ノード タイプ、および 2 つのタイプのダイアグラム接続を含む  _Basic Shapes_   と  _Connections_  ) があります。

==== 関連トピック:

* link:xamdiagram-configuring-the-toolbox.html[ツールボックスの構成 ( _xamDiagram_ )]

[[_Ref391538104]]

=== 元に戻す / やり直し

_xamDiagram_   コントロールでは、操作履歴を保持して元に戻す / やり直し操作を実行することで、元に戻す / やり直し機能がサポートされています。

Infragistics Undo/Redo Framework は、{ProductName} で元に戻す / やり直し機能を提供しています。

==== 関連トピック:

* link:xamdiagram-configuring-undo-redo-operations.html[元に戻す / やり直し操作の構成 ( _xamDiagram_ )]