////

|metadata|
{
    "name": "xamdatacarousel",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{0D7DF756-B06A-49C2-B796-FAEFAB858101}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.6298791Z"
}
|metadata|
////

= xamDataCarousel



xamDataCarousel™ コントロールに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このセクションをご覧ください。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamDataCarousel についての有益な情報を含んでいます。

以下のリンクをクリックして、xamDataCarousel コントロールについての情報にアクセスします。

== link:xamdatacarousel-understanding-xamdatacarousel.html[xamDataCarousel について]

このセクションでは、xamDataCarousel コントロールの機能をより良く理解するために助けとなるあらゆる情報や、アプリケーション構築の一環としてこのコントロールの機能を使いたくなる理由が説明されています。

== link:xamdatacarousel-getting-started-with-xamdatacarousel.html[xamDataTree をページに追加]

xamDataCarousel コントロールでできる限り素早く起動して実行するために、コントロールを使用して開始する方法 (たとえば、フォームに xamDataCarousel を追加) についての情報を提供します。

== link:xamdatacarousel-using-xamdatacarousel.html[xamDataCarousel の使用]

このセクションには、xamDataCarousel コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamdatacarousel-api-overview.html[API の概要]

このトピックは、xamDataCarousel コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックにリストされる名前空間とクラスは、{ProductName} ヘルプの link:api-reference-guide.html[API リファレンス ガイド]に便宜上リンクします。