////

|metadata|
{
    "name": "xamdatapresenter-load-field-customizations",
    "controlName": ["xamDataPresenter"],
    "tags": ["Layouts","Styling"],
    "guid": "{AB95F65A-2991-439C-9A0D-4D56B36D0572}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2470025Z"
}
|metadata|
////

= フィールド カスタマイズのロード



xamDataGrid™ コントロールまたは xamDataPresenter™ コントロールを使用して、エンドユーザーはランタイムにフィールドの移動、並べ替え、およびグループ化ができます。xamDataCarousel™ コントロールは、フィールドヘッダーを表示しないので、エンドユーザーにフィールドのグループ化だけを許可します。エンドユーザーは、アプリケーションの再起動時にフィールドを修正する必要がないように、これらのカスタマイズの保存およびロードを開発者に期待します。link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase.html[DataPresenterBase] クラスは、以前に保存したフィールドカスタマイズをロードするために使用できるオーバーロードされた link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~loadcustomizations.html[LoadCustomizations] メソッドを公開します。link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayout.html[FieldLayout] オブジェクトの link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayout~key.html[Key] プロパティがレイアウトファイルのキー値に一致しない場合、データ プレゼンターはレイアウト ファイルからのカスタマイズを適用しません。

以下のコード例は、フィールド カスタマイズをロードする方法を示します。コード例は xamDataGrid コントロールのインスタンスを使用しますが、xamDataPresenter コントロールまたは xamDataCarousel コントロールを使用できます。

*Visual Basic の場合:*

----
Imports System.IO
...
Using fs As New FileStream("xamDataGridLayout1.xml", FileMode.Open, FileAccess.Read) 
    Me.xamDataGrid1.LoadCustomizations(fs)                             
End Using 
...
----

*C# の場合:*

----
using System.IO;
...
//ストリームからレイアウトをロードします。
using(FileStream fs = new FileStream("xamDataGridLayout1.xml", FileMode.Open, FileAccess.Read))
{
    this.xamDataGrid1.LoadCustomizations(fs);
}
...
----

== 関連トピック

link:xamdatapresenter-define-a-field-layout.html[フィールド レイアウトの定義]

link:xamdatapresenter-save-field-customizations.html[フィールド カスタマイズの保存]