////

|metadata|
{
    "name": "xamdockmanager-pin-and-unpin-a-pane",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I"],
    "guid": "{CDC05C09-461F-458C-8BA5-20291C5DE951}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5140559Z"
}
|metadata|
////

= ペインのピンを固定および解除



xamDockManager™ コントロールを使用すれば、ピン固定されたコンテンツ ペインをピン固定を解除することで隠すことができます。同様に、常に表示可能になるように隠されたペインが飛び出す時にピン固定できます。コンテンツ ペインのピンの固定および解除はコードの中で実行するか、またはエンド ユーザーがランタイムに行うことができます。

以下のコード例は、コンテンツ ペインのピン固定を解除する方法を示します。

*XAML の場合:*

----
...
<igDock:XamDockManager Name="xamDockManager1"> 
    <igDock:XamDockManager.Panes>
        <igDock:SplitPane>
            <igDock:ContentPane 
                Name="contentPane1" 
                Header="Pane 1" 
                IsPinned=">
                <!--TODO: ここでコンテンツを追加します-->
            </igDock:ContentPane>
        </igDock:SplitPane>
    </igDock:XamDockManager.Panes>
</igDock:XamDockManager>
...
----

*Visual Basic の場合:*

----
Me.contentPane1.IsPinned = False
----

*C# の場合:*

----
this.contentPane1.IsPinned = false;
----

== 関連トピック

link:xamdockmanager-about-opening-and-closing-panes.html[開始ペインと終了ペインについて]

link:xamdockmanager-add-content-to-a-contentpane.html[コンテンツを ContentPane に追加]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[ペインを DocumentContentHost オブジェクトに追加]

link:xamdockmanager-add-panes-to-xamdockmanager.html[ペインを xamDockManager に追加]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[タブ付き MDI アプリケーションを作成]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[エンドユーザーがフローティング ペインのサイズを変更することを禁止]

link:xamdockmanager-set-the-location-of-a-floating-pane.html[フローティング ペインの場所を設定]

link:xamdockmanager-set-the-initial-location-of-a-pane.html[ペインの最初の位置を設定]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[フローティング ペインのサイズを設定]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[プログラミングによるペイン ナビゲータの表示]

link:xamdockmanager-end-user-settings.html[エンドユーザー設定]

link:xamdockmanager-styling-xamdockmanager.html[xamDockManager のスタイリング]