////

|metadata|
{
    "name": "xamdockmanager-set-the-initial-location-of-a-pane",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I"],
    "guid": "{BD27AFB5-FFDB-4D4A-A7DB-C7480BC9DB1B}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5250581Z"
}
|metadata|
////

= ペインの最初の位置を設定



xamDockManager コントロールは、デフォルトで link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~panes.html[Panes コレクション]のすべてのルートレベル分割ペインを左にドックします。これは、アプリケーションが起動するとすべてのコンテンツが左にドックされることを意味します。ただし、xamDockManager の link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~initiallocationproperty.html[InitialLocation] 添付プロパティを設定して、アプリケーションの起動時にアプリケーションの特定の側にルート レベルの分割ペインをドックしたり、ルート レベルの分割ペインをフロートすることができます。

InitialLocation 添付プロパティは、xamDockManager が分割ペインを Panes コレクションに追加後は効果を持ちません。InitialLocation 添付プロパティを XAML で設定するか、xamDockManager の Panes コレクションに動的にインスタンス化された分割ペインを追加する前に設定する必要があります。

以下のコードは、ペインの最初の場所を設定する方法を示します。

*XAML の場合:*

----
<igDock:XamDockManager Name="xamDockManager1">
    <igDock:XamDockManager.Panes>
        <igDock:SplitPane igDock:XamDockManager.InitialLocation="DockedRight">
            <igDock:ContentPane Header="Pane 1">
                <!--TODO: ここでコンテンツを追加します-->
            </igDock:ContentPane>
        </igDock:SplitPane>
    </igDock:XamDockManager.Panes>
</igDock:XamDockManager>
----

*Visual Basic の場合:*

----
Imports Infragistics.Windows.DockManager
...
Dim splitPane1 As New SplitPane() 
'分割ペインを Panes コレクションに追加する前に InitialLocation 添付プロパティを設定する必要があります。 
XamDockManager.SetInitialLocation(splitPane1, InitialPaneLocation.DockedRight) 
Me.xamDockManager1.Panes.Add(splitPane1) 
Dim contentPane1 As New ContentPane() 
contentPane1.Header = "Pane 1" 
splitPane1.Panes.Add(contentPane1)
...
----

*C# の場合:*

----
using Infragistics.Windows.DockManager;
...
SplitPane splitPane1 = new SplitPane();
//分割ペインを Panes コレクションに追加する前に InitialLocation 添付プロパティを設定する必要があります。
XamDockManager.SetInitialLocation(splitPane1, InitialPaneLocation.DockedRight);
this.xamDockManager1.Panes.Add(splitPane1);
ContentPane contentPane1 = new ContentPane();
contentPane1.Header = "Pane 1";
splitPane1.Panes.Add(contentPane1);
...
----

== 関連トピック

link:xamdockmanager-about-opening-and-closing-panes.html[開始ペインと終了ペインについて]

link:xamdockmanager-add-content-to-a-contentpane.html[コンテンツを ContentPane に追加]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[ペインを DocumentContentHost オブジェクトに追加]

link:xamdockmanager-add-panes-to-xamdockmanager.html[ペインを xamDockManager に追加]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[タブ付き MDI アプリケーションを作成]

link:xamdockmanager-pin-and-unpin-a-pane.html[ペインのピンを固定および解除]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[エンドユーザーがフローティング ペインのサイズを変更することを禁止]

link:xamdockmanager-set-the-location-of-a-floating-pane.html[フローティング ペインの場所を設定]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[フローティング ペインのサイズを設定]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[プログラミングによるペインナビゲータの表示]

link:xamdockmanager-end-user-settings.html[エンドユーザー設定]

link:xamdockmanager-styling-xamdockmanager.html[xamDockManager のスタイリング]