////

|metadata|
{
    "name": "xamdatapresenter-perform-an-auto-sizing-operation",
    "controlName": ["xamDataPresenter"],
    "tags": ["How Do I","Layouts","Tips and Tricks"],
    "guid": "{65ACB04F-93E9-4252-A5E7-A1E4D1104E9B}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2820095Z"
}
|metadata|
////

= 自動サイズ設定操作の実行



DataPresenter コントロールを使用すると、エンド ユーザーはフィールドのサイズ変更インジケーターをダブルクリックして、コンテンツがフィットするようにフィールドをサイズ変更できます。また、イベントを処理し、 link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[Field] オブジェクトの link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field~performautosize.html[PerformAutoSize] メソッドを呼び出すか、または、 link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresentercommands.html[DataPresenterCommands] クラスが公開する link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresentercommands~autosizefield.html[AutoSizeField] コマンドを実行することによって、この同じ機能を複製することもできます。

PerformAutoSize メソッドのパラメーターのないバージョンは、 link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings.html[FieldSettings] オブジェクトの link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~autosizeoptions.html[AutoSizeOptions] および link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~autosizescope.html[AutoSizeScope] プロパティを考慮します。そのため、あるフィールドの自動サイズ設定を無効にする場合、PerformAutoSize メソッドのパラメーターのないバージョンを呼び出してもそのフィールドには影響しません。ただし、PerformAutoSize メソッドにはオーバーロードがあり、AutoSizeOptions および AutoSizeScope の列挙値を渡すことで、フィールドの自動サイズ設定に関係なく、フィールドを自動サイズ設定できます。

AutoSizeField コマンドには、 link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[Field] オブジェクトをコマンドパラメーターとして渡す必要があります。フィールドが自動サイズ設定を許可しない場合、AutoSizeField コマンドは実行されません。

以下のコード例は自動サイズ設定操作を実行する方法を示します。このコード例は、アクティブな Cell オブジェクトの Field プロパティを使用して、PerformAutoSize メソッドを呼び出し、AutoSizeField コマンドを実行します。

*XAML の場合:*

----
<Button 
    Content="Auto-size the current field" 
    Command="{x:Static igDP:DataPresenterCommands.AutoSizeField}" 
    CommandTarget="{Binding ElementName=xamDataPresenter1}" 
    CommandParameter="{Binding ElementName=xamDataPresenter1, Path=ActiveCell.Field}" />
<igDP:XamDataPresenter Name="xamDataPresenter1" BindToSampleData="True">
</igDP:XamDataPresenter>
----

*Visual Basic の場合:*

----
If Me.xamDataPresenter1.ActiveCell IsNot Nothing Then
    ' 次のコマンドを実行します:
    'Me.xamDataPresenter1.ExecuteCommand(DataPresenterCommands.AutoSizeField, Me.xamDataPresenter1.ActiveCell.Field)
    Me.xamDataPresenter1.ActiveCell.Field.PerformAutoSize()
End If
----

*C# の場合:*

----
if(this.xamDataPresenter1.ActiveCell != null)
{
    // 次のコマンドを実行します:
    //this.xamDataPresenter1.ExecuteCommand(DataPresenterCommands.AutoSizeField, this.xamDataPresenter1.ActiveCell.Field);
    this.xamDataPresenter1.ActiveCell.Field.PerformAutoSize();
}
----

== 関連トピック

link:xamdatapresenter-set-a-fields-width.html[フィールドの幅の設定]

link:xamdatapresenter-automatically-fit-fields.html[自動的にフィールドを調整]

link:xamdatapresenter-modify-field-sizing-behaviors.html[フィールドのサイズ設定動作の修正]