////

|metadata|
{
    "name": "xamdialogwindow",
    "controlName": ["xamDialogWindow"],
    "tags": ["Getting Started"],
    "guid": "3ab6a1ea-8cb4-47e7-ab42-58ec44bafd4a",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9471229Z"
}
|metadata|
////

= xamDialogWindow

このセクションでは、xamDialogWindow™ の使用に関する概要を説明します。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamDialogWindow についての有益な情報を含んでいます。以下のリンクをクリックして、xamDialogWindow コントロールについての情報にアクセスします。

== link:xamdialogwindow-about-xamdialogwindow.html[xamDialogWindow について]

このセクションの説明を読むと、xamDialogWindow コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

== link:xamdialogwindow-adding-xamdialogwindow-to-your-page.html[xamDialogWindow をアプリケーションに追加]

xamDialogWindow コントロールを使ってすばやく起動して実行するためのコントロールの使用方法を提供します。

== link:xamdialogwindow-using-xamdialogwindow.html[xamDialogWindow の使用]

このセクションには、xamDialogWindow コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamdialogwindow-api-overview.html[API の概要]

このトピックは、xamDialogWindow コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックに挙げられている名前空間とクラスは、{ProductName} ヘルプの「API リファレンス ガイド」セクションにリンクされています。