////

|metadata|
{
    "name": "xamgantt-calendars-configuration-overview",
    "controlName": ["xamGantt"],
    "tags": ["Data Binding","Data Presentation","Formatting","Grids","Scheduling"],
    "guid": "f02315e7-8a55-4615-8cf8-f8160f17c33b",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.4751771Z"
}
|metadata|
////

= カレンダー構成の概要 (xamGantt)

== トピックの概要

=== 目的

このトピックでは、 _xamGantt_™ カレンダーの主要な機能の概要を提供します。xamGantt はカレンダーを使用して時間計算を行います。

=== 本トピックの内容

このトピックには次のセクションがあります。

* <<_Calendars_Overview, カレンダーの概要 >>

** <<_xamGantt_Calendars,xamGantt カレンダー>>

** <<_Project_Calendar,プロジェクト カレンダー>>

** <<_Custom_Calendar,カスタム カレンダー>>

* <<_Related_Content, 関連コンテンツ >>

[[_Calendars_Overview]]
== カレンダーの概要

[[_xamGantt_Calendars]]

=== xamGantt カレンダー

カレンダーは、タスク期間を Start 値に追加するなど、時間計算を行うために xamGantt によって使用されます。時間計算はタスク、プロジェクト、リソース設定に基づいて行われます。カレンダーを設定するために link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectcalendar_members.html[ProjectCalendar] クラスを使用する、またはカスタムのカレンダー クラスを作成できます。

`ProjectCalendar` を使用して、 link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectcalendar~daysofweek.html[DaysOfWeek] プロパティと link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectcalendar~workweeks.html[WorkWeeks] プロパティを使用して、週の曜日に関する稼働時間情報を指定できます。

以下の表に xamGantt とカレンダーを使用する時の主要な点をまとめます。

[options="header", cols="a,a"]
|====
|機能|説明

|ProjectCalendar
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.project_members.html[Project] の稼働時間情報を表すために `ProjectCalendar` クラスを使用できます。

|カスタム カレンダー
|カスタム クラスを作成してカレンダーとして使用できます。

|使用されるカレンダーを決定
|時間計算を実行するために xamGantt はカレンダーを必要とします。プロジェクトにカレンダーが設定され、すべての時間計算はこのカレンダーに基づきます。

|====

[[_Project_Calendar]]

=== プロジェクト カレンダー

`DaysOfWeek` プロパティを設定することによって曜日の稼働時間情報を設定し、 link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectcalendar~exceptions.html[Exceptions] プロパティを使用して特定の繰り返しパターンで稼働時間を調整し、 link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectcalendar~displayname.html[DisplayName] プロパティによってユーザー カレンダー名を指定し、`WorkWeeks` プロパティを使用して特定の日付範囲で曜日のために稼働時間のコレクションを取得することができます。

*関連トピック*

link:xamgantt-configuring-the-xamgantt-project-calendar.html[xamGantt ProjectCalendar の構成]

[[_Custom_Calendar]]

=== カスタム カレンダー

カスタム カレンダーを作成して xamGantt と使用できます。

*関連トピック*

link:xamgantt-configuring-custom-calendars-for-xamgantt.html[xamGantt カスタム カレンダーの構成]

[[_Related_Content]]
== 関連コンテンツ

このトピックについては、以下のトピックも参照してください。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xamgantt-configuring-the-xamgantt-calendars.html[xamGantt カレンダーの構成]
|このグループのトピックには、 _xamGantt_ カレンダーの情報が含まれています。

|====
