////

|metadata|
{
    "name": "xamgrid-disable-resizing-of-certain-columns",
    "controlName": ["xamGrid"],
    "tags": ["Editing","Grids","How Do I","Layouts"],
    "guid": "{BF6F968A-127E-426A-BF2D-E2922825D6C0}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.8471657Z"
}
|metadata|
////

{XamGridHeader}

= 特定の列のサイズ変更を無効にする

グリッド全体で列のサイズ変更が有効になっていても、xamGrid コントロールで特定の列のサイズ変更を無効にすることができます。たとえば、並べ替えた列があり、エンド ユーザーがその列のサイズを変更できないようにするとします。

これを達成するには、以下のコードに示すように link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.column.html[Column] オブジェクトの link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.column~isresizable.html[IsResizable] プロパティを False に設定することができます。

*XAML の場合:*

----
<ig:XamGrid x:Name="MyGrid" AutoGenerateColumns="False">
   <ig:XamGrid.ColumnResizingSettings>
      <ig:ColumnResizingSettings AllowColumnResizing="Indicator" AllowCellAreaResizing="True" AllowMultipleColumnResize="True" AllowDoubleClickToSize="True"/>
   </ig:XamGrid.ColumnResizingSettings>
   <ig:XamGrid.Columns>
      <ig:TextColumn Key="ProductID"/>
      <ig:TextColumn Key="ProductName" IsResizable="/>
      ...
   </ig:XamGrid.Columns>
</ig:XamGrid>
----

*Visual Basic の場合:*

----
Imports Infragistics.Controls.Grids
...
Dim ColumnNotResizable As Column = Me.MyGrid.Columns.DataColumns("ProductName")
ColumnNotResizable.IsResizable = False        
----

*C# の場合:*

----
using Infragistics.Controls.Grids;
...
Column ColumnNotResizable = this.MyGrid.Columns.DataColumns["ProductName"];
ColumnNotResizable.IsResizable = false;
----

== 関連トピック

link:xamgrid-column-resizing.html[列サイズの変更]

link:xamgrid-multi-column-resizing.html[複数列のリサイズ]

link:xamgrid-resize-in-the-cell-area.html[セル領域でセルのリサイズ]

link:xamgrid-auto-size-columns-using-mouse-clicks.html[マウス クリックを使用して列を自動的にサイズ設定]

link:xamgrid-set-columns-maximum-and-minimum-widths.html[列の最大幅と最小幅を設定]

link:xamgrid-column-resizing-events.html[列のサイズ変更イベント]