////

|metadata|
{
    "name": "xamgrid-resize-in-the-cell-area",
    "controlName": ["xamGrid"],
    "tags": ["Grids","How Do I","Layouts"],
    "guid": "{1A356826-8876-4B67-ABE4-E5C96F7265CE}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.841165Z"
}
|metadata|
////

{XamGridHeader}

= セル領域でセルのリサイズ

xamGrid コントロールを使用する場合、セルのサイズ変更を有効にすることができます。この機能によってヘッダーのリサイズだけでなく各セルもリサイズできます。

これは、エンド ユーザーがセルに含まれるデータを読み込むことができない場合、セルを希望の幅にサイズ変更できる便利な機能です。

エンド ユーザーがセルのサイズを変更すると、列全体のサイズも変更されます。

セルのサイズ変更を有効にするには、 link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.columnresizingsettings.html[ColumnResizingSettings] オブジェクトの link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.columnresizingsettings~allowcellarearesizing.html[AllowCellAreaResizing] プロパティを True に設定します。

*XAML の場合:*

----
<ig:XamGrid x:Name="MyGrid">
   <ig:XamGrid.ColumnResizingSettings>
      <ig:ColumnResizingSettings AllowColumnResizing="Indicator" 
            AllowCellAreaResizing="True"/>
   </ig:XamGrid.ColumnResizingSettings>
…   
</ig:XamGrid>
----

*Visual Basic の場合:*

----
Me.MyGrid.ColumnResizingSettings.AllowCellAreaResizing = True
----

*C# の場合:*

----
this.MyGrid.ColumnResizingSettings.AllowCellAreaResizing = true;
----

== 関連トピック

link:xamgrid-column-resizing.html[列サイズの変更]

link:xamgrid-multi-column-resizing.html[複数列のリサイズ]

link:xamgrid-auto-size-columns-using-mouse-clicks.html[マウス クリックを使用して列を自動的にサイズ設定]

link:xamgrid-set-columns-maximum-and-minimum-widths.html[列の最大幅と最小幅を設定]

link:xamgrid-disable-resizing-of-certain-columns.html[特定の列のサイズ変更を無効にする]

link:xamgrid-column-resizing-events.html[列のサイズ変更イベント]

pick:[win-rt=" link:xamgrid-touch-support.html[タッチ サポート]"]