////

|metadata|
{
    "name": "xammap",
    "controlName": ["xamMap"],
    "tags": ["Getting Started"],
    "guid": "{D6B680C7-BC02-4317-A2BE-B4D73CA1976C}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.3112388Z"
}
|metadata|
////

= xamMap

このセクションは、 link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.xammap.html[xamMap] コントロールの概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順を提供します。

xamMap コントロールは、マップの形式でデータを表示します。マップの形状は、点、線分群、多角形を記述する地理空間ベクトル データ フォーマットである Shapefile に依存します。点は市を描画し、線分群は道路を描画し、多角形は州を描画します。

xamMap コントロールはマップの形状を視覚化するためにマップ投影法を使用します。SphericalMercator プロジェクトは、デフォルト マップ プロジェクトです。このコントロールは、さまざまな座標系でシェープ ファイルを読み込むだけでなく、マップ投影法を選択してマップを表示できます。更に、xamMap は外部ソースの地図画像データを表示できます。

形状データの表示に加えて、xamMap は魅力があって生産性の高いマップを表示および操作する保有機能を提供します。これらの機能は以下のとおりです。

* *レイヤーの割り当て* - 複数のマップを使用して、州、市、および道路などのマップ 要素の複雑なレイヤー化を行うことができます。
* *地図画像* - 地図画像マップを使用して、地形のタイプ、道路のタイプ/名前、建物のタイプなどのより複雑なマップ要素さえ可能です。
* *インタラクティブなマップ 要素* - マップの図形の表現はユーザーのアクションに対応することができ、ユーザー エクスペリエンスを高めます。
* *包括的な色モード* - マップ 要素に色を付けるため、マップの表現は豊かでありながらシンプルな方法で拡張されます。
* *データ バインド* - Shapefiles および地図画像からのデータに加えて、xamMap は、データ バインディングおよびデータ マッピング機能を使用してマップ要素と他のデータ ソースを関連付けることができます。
* *ヘルパー ペインおよび子コントロール* - ナビゲーション、色見本、サムネイル、およびスケール ペインなどのユーザー エクスペリエンスをさらに拡張するために、追加的なコントロールを xamMap コントロール ライブラリで使用できます。

以下のリンクをクリックして、xamMap コントロールについての情報にアクセスします。

== link:xamwebmap-understanding-xamwebmap.html[xamMap について]

このセクションの説明を読むと、xamMap コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

== link:xamwebmap-getting-started-with-xamwebmap.html[xamTree を使用した作業の開始]

xamMap コントロールをすばやく起動して実行するためのコントロールの使用方法を提供します。

== link:xamwebmap-using-xamwebmap.html[xamMap の使用]

このセクションには、xamMap コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamwebmap-api-overview.html[API の概要]

このトピックは、xamMap コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックの名前空間とクラスの一覧は、{ProductName} ヘルプの link:xamwebmap-api-overview.html[API リファレンス ガイド]へリンクします。