////

|metadata|
{
    "name": "xampivotgrid",
    "controlName": ["xamPivotGrid"],
    "tags": ["Getting Started"],
    "guid": "{E357E246-DE9D-48EB-8AD2-21B26F3DF4C3}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.2523286Z"
}
|metadata|
////

= xamPivotGrid

このセクションは、 link:{ApiPlatform}controls.grids.xampivotgrid{ApiVersion}~infragistics.controls.grids.xampivotgrid.html[xamPivotGrid] コントロールの使用に関する概要を提供します。このセクションには、コントロールが行うことやコントロールをアプリケーションで使用する理由から、コントロールを使用して共通タスクを達成するための方法の手順など、xamPivotGrid に関する有益な情報が含まれています。

以下のリンクをクリックして、xamPivotGrid コントロールに関する情報にアクセスします。

== link:xampivotgrid-understanding-xampivotgrid.html[xamPivotGrid の理解]

このセクションの説明を読むと、xamPivotGrid コントロールの機能性と、それをアプリケーション構築に使用する利点についてよく理解できます。

== link:xampivotgrid-getting-started-with-xampivotgrid.html[xamPivotGrid を使用した作業の開始]

xamPivotGrid コントロールをすばやく起動して実行するためのコントロールの使用方法を提供します。

== link:xampivotgrid-using-xampivotgrid.html[XamPivotGrid の使用]

このセクションには、xamPivotGrid コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xampivotgrid-api-overview.html[API の概要]

このトピックは、xamPivotGrid コントロールの開発で使用する名前空間とクラスの一覧を示します。このトピックの名前空間とクラスの一覧は、{ProductName} ヘルプの link:api-reference-guide.html[API リファレンス ガイド]へリンクします。