////

|metadata|
{
    "name": "xampropertygrid-commands",
    "tags": ["Commands","How Do I"],
    "controlName": ["xamPropertyGrid"],
    "guid": "1e847edb-ef6f-4949-bf44-82d3273a7ea4",  
    "buildFlags": [],
    "createdOn": "2014-08-28T11:08:01.036596Z"
}
|metadata|
////

= コマンドの操作 (xamPropertyGrid)

== トピックの概要

=== 目的

このトピックでは、コマンドによりコントロールを使用してさまざまな操作を実行する方法を説明します。

=== 前提条件

このトピックを理解するために、以下のトピックを参照することをお勧めします。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xampropertygrid-features-overview.html[機能の概要 (xamPropertyGrid)]
|このトピックでは、このコントロールでサポートする機能を開発者の観点から説明します。

| link:xampropertygrid-visual-elements.html[視覚要素 (xamPropertyGrid)]
|このトピックでは、コントロールの視覚要素についての概要を紹介します。

|====

=== このトピックの内容

このトピックは、以下のセクションで構成されます。

* <<_Ref394931540, コマンドの概要 >>
* <<_Ref394931554, コード例:XAML でのコマンドの呼び出し >>
* <<_Ref394931560, コード例:パラメーターを使用した XAML でのコマンドの呼び出し >>
* <<_Ref394931561, コード例:コードでのコマンドの呼び出し >>
* <<_Ref394931565, 関連コンテンツ >>

[[_Ref394931540]]
== コマンドの概要

=== コマンドの概要

link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.xampropertygrid_members.html[ _xamPropertyGrid_  ] コントロールは、さまざまな機能を起動するコマンドを提供します。すべてのコマンドのリストは、 link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridcommandtype.html[PropertyGridCommandType] にあります。

link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.primitives.propertygridcommandsource_members.html[PropertyGridCommandSource] タイプをインスタンス化することにより、コマンドを起動できます。ただし、以下のコマンドは、 link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridpropertyitem_members.html[PropertyGridPropertyItem] パラメーターを必要とし、 link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.primitives.propertygridpropertyitemcommandsource_members.html[PropertyGridPropertyItemCommandSource] タイプをインスタンス化することにより起動されます。

* `AddListEntry`
* `RemoveListEntry`
* `ResetPropertyValue`
* `CreateExpandableObject`
* `ShowOptionsMenu`

[[_Ref394931554]]
== コード例:XAML でのコマンドの呼び出し

=== 説明

以下のコードは、ボタンを使用して  _xamPropertyGrid_   コントロールに対して XAML でコマンドを呼び出す方法を示します。このコードは、「xamPropertyGrid1」という名前の  _xamPropertyGrid_   のインスタンスへの参照があることを前提としています。

=== コード

*XAML の場合:*

[source,xaml]
----
<Page
  …
  xmlns:ig="http://schemas.infragistics.com/xaml"
  xmlns:igPrim="http://schemas.infragistics.com/xaml/primitives"
  …>
<Button
  Content="Sort By Category"
  ig:Commanding.CommandTarget="{Binding ElementName=xamPropertyGrid1}">
  <ig:Commanding.Command>
    <igPrim:PropertyGridCommandSource
      EventName="Click"
      CommandType="SortByCategory" />
  </ig:Commanding.Command>
</Button>
----

[[_Ref394931560]]
== コード例:パラメーターを使用した XAML でのコマンドの呼び出し

=== 説明

以下のコードは、ボタンを使用して  _xamPropertyGrid_   コントロールに対して XAML でパラメーターを含むコマンドを呼び出す方法を示します。このコードは、「xamPropertyGrid1」という名前の  _xamPropertyGrid_   のインスタンスへの参照があることを前提としています。

=== コード

*XAML の場合:*

[source,xaml]
----
<Page
  …
  xmlns:ig="http://schemas.infragistics.com/xaml"
  xmlns:igPrim="http://schemas.infragistics.com/xaml/primitives"
  …>
<Button
  Content="Reset Current Property Value"
  ig:Commanding.CommandTarget="{Binding ElementName=xamPropertyGrid1}">
  <ig:Commanding.Command>
    <igPrim:PropertyGridPropertyItemCommandSource
      EventName="Click"
      CommandType="ResetPropertyValue"
      ParameterBinding="{Binding ElementName=xamPropertyGrid1, Path=SelectedItem}" />
  </ig:Commanding.Command>
</Button>
----

[[_Ref394931561]]
== コード例:コードでのコマンドの呼び出し

=== 説明

以下のコードは、  _xamPropertyGrid_   コントロールに対してコードでコマンドを呼び出す方法を示します。このコードは、「xamPropertyGrid1」という名前の  _xamPropertyGrid_   のインスタンスへの参照があることを前提としています。

=== コード

以下のコードはこの例を実装します。

*C# の場合:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Controls.Editors.Primitives;
...
PropertyGridCommand cmd = new PropertyGridCommand(PropertyGridCommandType.SortByCategory);
cmd.Execute(this.xamPropertyGrid1);
----

*Visual Basic の場合:*

[source,vb]
----
Import Infragistics.Controls.Editors
Import Infragistics.Controls.Editors.Primitives
...     
Dim cmd As New PropertyGridCommand(PropertyGridCommandType.SortByCategory)
cmd.Execute(Me.xamPropertyGrid1)
----

[[_Ref394931565]]
== 関連コンテンツ

=== トピック

このトピックの追加情報については、以下のトピックも合わせてご参照ください。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xampropertygrid-work-expandable-properties.html[展開可能なプロパティのサポート (xamPropertyGrid)]
|このトピックでは、コントロールが展開可能なプロパティを識別し表示する方法を説明します。

| link:xampropertygrid-property-item-generators.html[プロパティ項目ジェネレーター (xamPropertyGrid)]
|このトピックでは、コントロールが選択されたオブジェクトのプロパティを検出する方法、プロパティ項目のリストを作成する方法、およびプロセスを構成しカスタマイズする方法を説明します。

| link:xampropertygrid-resetting-property-value.html[プロパティ値のリセット (xamPropertyGrid)]
|このトピックでは、プロパティの既定値を定義する方法と、オプション メニューをカスタマイズする方法を説明します。

|====