////

|metadata|
{
    "name": "xamribbon-ribbon-tabs",
    "controlName": ["xamRibbon"],
    "tags": ["Grouping"],
    "guid": "{8B852806-94D6-4A0A-910D-863D23E4BE73}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1991929Z"
}
|metadata|
////

= リボン タブ



xamRibbon™ のメイン クライアント領域は、1 つ以上のタブで構成されます。各タブは複数のグループを含むことができます。グループはツールを含みます -- 論理的なセクションに分割します。タブによってツールの複数のグループを作ることができますが、すべてはワープロ アプリケーションの特定の作業など、共通のテーマの作業をしなければなりません。すべてのタブはグループを含みますが、すべてのタブは等しく作成されるわけではありません。

コンテキスト タブは、デフォルトでエンドユーザーに表示されないタブの特別なタイプです。コンテキスト タブを表示するには、エンド ユーザーは特定の作業を実行する必要があり、アプリケーションを特定の状態に置く必要があります。言い換えると、コンテキスト タブは一定のコンテキストに限り表示されます。たとえば、描画テーブルに関連するツールを持ったタブやエンド ユーザーが形状を描画する支援をするツールのタブがあります。ただし、エンド ユーザーが頻繁に使用する必要がある他のタブも複数あります。エンド ユーザーはテーブルを持たない、または文書で描画を全くしない場合があります。したがって、表や形状タブを表示する必要はありません。表や描画などの文書にオブジェクトをユーザーが挿入する支援をする挿入タブがあります。エンド ユーザーが表挿入ボタンをクリックすると、アプリケーションは表を挿入してそれを選択すると、表タブを表示できます。このケースでは、表のコンテキストに限り表示するので、コンテキスト タブを検討します。

興味がある場合、xamRibbon のタブについての詳細は、以下のトピックを参照してください。

* link:xamribbon-add-a-tab-to-xamribbon.html[タブを xamRibbon に追加]
* link:xamribbon-add-a-contextual-tab-to-xamribbon.html[コンテキスト タブを xamRibbon に追加]
* link:xamribbon-showing-a-contextual-tab-group-programmatically.html[コンテキスト タブ グループをプログラムで表示]