////

|metadata|
{
    "name": "xamribbon-about-xamribbon",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started"],
    "guid": "{C4741F6B-F571-4E6C-93CB-FCA92E63FCD3}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0891709Z"
}
|metadata|
////

= xamRibbon について

xamRibbon™ コントロールは、多くのユーザー操作を必要とするユーザー インターフェイスのための完全なナビゲーション パラダイムです。ただし、xamRibbon は単なるコントロールではありません。xamRibbon ウィンドウからの助けを受けてユーザー インターフェイス全体を含みます。xamRibbon は Microsoft® Office® のユーザーに馴染みがありますが、Infragistics の工夫が追加され、ユーザーが必要とするユーザー インターフェイスだけを入手できます。xamRibbon のユニークな Tab および Group 構造を使用すれば、特に必要な時だけ表示するコンテキスト タブでは、ツールを配置するための場所が足りなくなることはありません。

== タブとグループ

タブとグループは xamRibbon のメイン クライアント領域です。タブによって、エンド ユーザーは簡単にナビゲートしたり、手近でタスクに適切なツールを見つけることができます。各タブ内では、グループがアプリケーション ロジックを実行するツールを持ちます。

== アプリケーション メニュー

アプリケーションのトップにあるメイン メニュー バーにうんざりしていませんか？xamRibbon コントロールのアプリケーション メニューは、メイン メニューをひとつにきちんと整理し、ユーザーがアプリケーション メニュー ボタンをクリックすると視覚的に魅力的なドロップダウン メニューを表示します。

== クイック アクセス ツールバー

Quick Access Toolbar (QAT) を忘れないようにしましょう。これは xamRibbon の上または下にフローティングされる完全にカスタマイズ可能なツールバーです。QAT の唯一の存在目的は、開発者やエンド ユーザーが頻繁に使用するツールを追加して、後で簡単にアクセスできるようにすることです。xamRibbon コントロール全体を折り畳んで QAT でお気に入りのすべてのツールを使用できます。

== 関連トピック

link:xamribbon-adding-xamribbon-to-your-application-.html[xamRibbon をアプリケーションに追加]

link:xamribbon-using-xamribbon.html[xamRibbon の使用]