////

|metadata|
{
    "name": "xamribbon-key-tips",
    "controlName": ["xamRibbon"],
    "tags": ["How Do I"],
    "guid": "{F316BD48-3F0D-48CD-BBFE-17C4F761A2EB}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1741879Z"
}
|metadata|
////

= キー チップ



キー チップは、メイン メニュー バーのひとつの代用です (他のの代用は link:xamribbon-application-menu.html[アプリケーション メニュー])。エンドユーザーはメイン メニュー ニーモニックを使用して、キーストロークからメニュー項目に素早くアクセスします。通常、最初に Alt キーを押してニーモニックにアクセスします。Alt キーを押すと、メイン メニューの特定の文字 (つまり、ファイルでは 'F'、編集では 'E') に下線が付けられ、ニーモニックとしてその文字が識別されます。下線付きの文字を押し続けてメイン メニューからナビゲートします。キーチップはまったく同じように動作します。

xamRibbon™ を使用して、Alt キーを押すと、連続する 1 ～ 3 文字が収まるのに十分なほどの大きさの、非常に小さいツールチップが各タブ、グループ、およびツールに表示されます。キーチップは、アプリケーション メニュー ボタンおよびクイック アクセス ツールバーにも表示されます。タブの適切なキーを押すと、そのタブが未だアクティブでなければアクティブになります。関連付けられたタブのグループのキーチップがこれで表示されます。

自動生成が気に入らない場合、これらのキーチップをカスタマイズするオプションもあります。xamRibbon のほぼすべての要素は KeyTip プロパティを公開します。要素のキーチップを設定するには、1 文字から 3 文字を含む文字列に KeyTip プロパティを設定するだけです。

興味がある場合、xamRibbon のキーチップについての詳細は、以下のトピックを参照してください。

* link:xamribbon-display-custom-key-tips.html[カスタム キーチップを表示]
* link:xamribbon-display-a-segmented-key-tip-on-a-menu-tool.html[メニュー ツールでセグメント化されたキーチップを表示]