////

|metadata|
{
    "name": "xamspellchecker-performance-options",
    "controlName": ["xamSpellChecker"],
    "tags": ["Performance"],
    "guid": "{7C603037-C504-49B6-BFDB-65D020EE5A40}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.1513817Z"
}
|metadata|
////

= パフォーマンス オプション

xamSpellChecker™ コントロールによって、コントロールのパフォーマンスを高めるためのさまざまな方法を使用できます。これによって、ユーザー エクスペリエンスが全般的に改善されます。link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions.html[PerformanceOptions] オブジェクトは複数のプロパティを公開し、何をチェックして、何をチェックしないか、そしてどのようなタイプの修正候補を示すかなどをスペルチェックのエンジンに指示します。

以下の表は、各プロパティ、デフォルト値、およびパフォーマンスに各プロパティがどのような影響を与えるかを理解する手助けとなる事例を説明します。

[options="header", cols="a,a,a,a"]
|====
|プロパティ|デフォルト値|説明|例

| link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions~allowcapitalizedwords.html[AllowCapitalizedWords]
|False
|xamSpellChecker コントロールは、すべての大文字が含まれる単語のスペルをチェックします。このプロパティを True に設定すると、すべての大文字は無視されるので、パフォーマンスが向上します。
|AJAX 

ATLAS 

XML

| link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions~checkcompoundwords.html[CheckCompoundWords]
|False
|xamSpellChecker コントロールは、複合語をスペルミスとしてマークします。ただし、ドイツ語などの (複合された単語が使用される) 複数の言語に対してこのプロパティを True に設定することは非常に重要です。たとえば、Example 列の単語は、このプロパティを True に設定するとスペルミスでないと判断されます。注: このプロパティを Ture に設定すると、パフォーマンスが大幅に低下します。
|Helloworld 

Tooltips 

CheckCompoundWords

| link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions~considerationrange.html[ConsiderationRange]
|80
|xamSpellChecker コントロールはスペルミスの単語に対して最大 80 文字で修正候補の単語を検討します。このプロパティを小さい値に設定すると、修正候補を検索する速度は速くなりますが、修正候補は少ししか表示されません。この値をランタイムにマイナスの値に設定すると、80 にデフォルト設定されます。
|ConsiderationRange が 3 でスペルミスの単語が 'carr' である場合、xamSpellChecker は 'car' を提案します。ConsiderationRange が 4 に設定されている場合、xamSpellChecker は 'care' と 'car' を提案します。

| link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions~splitwordthreshold.html[SplitWordThreshold]
|2
|このプロパティは提案できる単語の最低のサイズを決定します。SuggestSplitWords は、このプロパティを使用するために Ture に設定する必要があります。
|SplitWordThreshold = 2 Asfault ('As fault' が提案されます) 

SplitWordThreshold = 3 Asfault ('As fault' は提案されません)

| link:{ApiPlatform}controls.interactions.xamspellchecker{ApiVersion}~infragistics.controls.interactions.performanceoptions~suggestsplitwords.html[SuggestSplitWords]
|True
|xamSpellChecker コントロールは、結合した単語が 2 つの区切られた単語であると確認できれば、分割した単語が修正候補として表示されます。CheckCompoundWords は、このプロパティが使用されるために、False に設定する必要があります。
|'helloword' は 'hello world' という修正候補になります。

|====

以下のコード例は、xamSpellChecker コントロールにさまざまなパフォーマンス オプションを設定する方法を示します。

*XAML の場合:*

----
<ig:XamSpellChecker Name="MySpellChecker">
       <ig:XamSpellChecker.PerformanceOptions>
              <ig:PerformanceOptions AllowCapitalizedWords="True" CheckCompoundWords="True" ConsiderationRange="10" SplitWordThreshold="3" SuggestSplitWords="True"></ig:PerformanceOptions>
        </ig:XamSpellChecker.PerformanceOptions>
   ...       
</ig:XamSpellChecker>
----

*Visual Basic の場合:*

----
Me.MySpellChecker.PerformanceOptions.AllowCapitalizedWords = True
Me.MySpellChecker.PerformanceOptions.ConsiderationRange = 10
Me.MySpellChecker.PerformanceOptions.SuggestSplitWords = True
Me.MySpellChecker.PerformanceOptions.SplitWordThreshold = 3
Me.MySpellChecker.PerformanceOptions.CheckCompoundWords = True   
----

*C# の場合:*

----
this.MySpellChecker.PerformanceOptions.AllowCapitalizedWords = false;
this.MySpellChecker.PerformanceOptions.ConsiderationRange = 10;
this.MySpellChecker.PerformanceOptions.SuggestSplitWords = true;
this.MySpellChecker.PerformanceOptions.SplitWordThreshold = 3;
this.MySpellChecker.PerformanceOptions.CheckCompoundWords = true;
----

== 関連トピック

link:xamspellchecker-spelling-options.html[スペル オプション]

link:xamspellchecker-how-to-specify-text-to-be-spell-checked.html[テキストをスペルチェックするように指定する方法]

link:xamspellchecker-dictionaries.html[辞書]