////
|metadata|
{
    "name": "xamsparkline-adding-xamsparkline",
    "controlName": ["xamSparkline"],
    "tags": ["Charting","Getting Started"],
    "guid": "81ddee34-34ab-4723-bd2b-ca9a43ccfbcd",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.2873585Z"
}
|metadata|
////

= xamSparkline を追加

== トピックの概要

=== 目的

このトピックは、 link:{ApiPlatform}controls.charts.xamsparkline{ApiVersion}.html[xamSparkline] コントロールの追加方法の概要を説明し、使用できる追加オプションを紹介します。

=== 前提条件

以下の表に、このトピックを理解するための前提条件として求められる素材をリストします。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xamsparkline-xamsparkline-overview.html[xamSparkline の概要]
|このトピックは、 _xamSparkline_ コントロールの概要、その利点、およびサポートされるチャート タイプを提供します。

| link:xamsparkline-configuring-xamsparkline.html[xamSparkline を構成]
|このトピックは、 _xamSparkline_ コントロールを構成するあらゆる方法の概要について説明します。構成の詳細情報へのリンク (別のトピックで参照可能) も記載されています。

|====

=== 本トピックの内容

このトピックには次のセクションがあります。

* <<_Ref317075029,Sparkline の追加>>

** <<Introduction,概要>>
** <<_Ref317075452,要件>>
** <<_Ref320180895,xamSparkline コントロールを追加する場合のオプション>>

* <<_Ref317075104,関連コンテンツ>>

[[_Ref317075029]]
== Sparkline の追加

=== 概要

Sparkline は、スタンドアロン コントロールとして、グリッド セルやテキスト付きのインラインなど、{PlatformName} アプリケーションの小さなスペースに表示できます。_xamSparkline_   コントロールは、コード内 (C# または Visual Basic) だけでなく、XAML からも追加できます。

どのデータを表示するか判断するには、データ ポイントとしてクラスに少なくとも 2 つの数値フィールドがあるデータ ソースが必要です。これは、それぞれ ItemsSource プロパティと link:xamsparkline-xamsparkline-property-reference.html#ValueMemberPath[ValueMemberPath] プロパティで処理されます。_xamSparkline_   コントロールを構成するには、最低でもこれらのプロパティ セットが必要です。

_xamSparkline_   コントロールの追加に必要なプロジェクト要件として、アセンブリ参照と名前空間の追加、さらにデータ要件がいくつかあります。

チャートを描画するためにデータに少なくとも 2 つの数値フィールドが含まれている限り、 _xamSparkline_   は一次元のデータ ソースをサポートします。

[[_Ref317075452]]

=== 要件

[start=1]

. 以下の NuGet パッケージ参照をアプリケーションに追加します。

** Infragistics.WPF.Sparkline

+
NuGet フィードのセットアップと NuGet パッケージの追加の詳細については、link:nuget-feeds.html[NuGet フィード] ドキュメントを参照してください。

[start=2]

. 以下の名前空間への参照を追加します。
+
*XAML の場合:* 

+
[source,xaml]
---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
---- 

[start=3]
. 1 次元数値のデータ ソースを含めます。*注:* Win/Loss 型のスパークラインの場合、最も大きな値と最も小さな値の 2 つの値だけがチャートに使用されます。データセットの残りの値は無視されます。

[[_Ref320022805]]

=== xamSparkline コントロールを追加する場合のオプション

以下の表は、 _xamSparkline_   コントロールの追加方法を示しています。

[options="header", cols="a,a"]
|====
|例|説明

| link:xamsparkline-adding-a-sparkline-to-a-page.html[xamSparkline をページに追加]
|一次元データを使用して、 _xamSparkline_ コントロールを直接ページに追加できます。

ifdef::sl,wpf[]
| link:xamgrid-sparkline-column.html[スパークライン列]
|Sparkline column 型を使用して、 _xamSparkline_ コントロールを _xamGrid_™ セルに追加できます。
endif::sl,wpf[]

|====

[[_Ref317075039]]

[[_Ref317075104]]
== 関連コンテンツ

=== トピック

以下のトピックでは、このトピックに関連する情報を提供しています。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:xamsparkline-xamsparkline-property-reference.html[xamSparkline プロパティ参照]
|このトピックは、 _xamSparkline_ コントロールの主なプロパティを説明します。

ifdef::sl,wpf[]
| link:xamgrid-sparkline-column.html[Sparkline Column]
|このトピックは、 _xamGrid_ コントロールの Sparkline column 型を紹介し、その使用方法を示します。
endif::sl,wpf[]

|====