////

|metadata|
{
    "name": "xamslider",
    "controlName": ["xamSlider"],
    "tags": [],
    "guid": "{A700DB6F-4447-4D1F-9FA9-5370CB9FFB0F}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.9913329Z"
}
|metadata|
////

= xamSlider

このセクションは、xamSlider の使用に関する概要を提供します。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamSlider についての有益な情報を含んでいます。以下のリンクをクリックして、xamSlider コントロールについての情報にアクセスします。

== link:xamslider-about-xamslider.html[xamSlider について]

このセクションの説明を読むと、xamSlider コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

== link:xamslider-getting-started-with-xamslider.html[xamSlider を使用した作業の開始]

xamSlider コントロールでできる限り素早く起動して実行するために、コントロールを使用して開始する方法 (たとえば、アプリケーションに単一値スライダーを追加) についての情報を提供します。

== link:xamslider-using-xamslider.html[xamSlider の使用]

このセクションには、xamSlider コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamslider-api-overview.html[API の概要]

このトピックは、xamSlider コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックに挙げられている名前空間とクラスは、{PlatformName} ヘルプの「API リファレンス ガイド」セクションにリンクされています。