////

|metadata|
{
    "name": "xamslider-retrieve-the-thumb-values",
    "controlName": ["xamSlider"],
    "tags": ["Getting Started","How Do I"],
    "guid": "{D7A28210-6E62-4C80-B12E-57761FB770C4}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.0793796Z"
}
|metadata|
////

= つまみの値の取得

link:{ApiPlatform}controls.editors.xamslider{ApiVersion}~infragistics.controls.editors.xamsimplesliderbase`1~thumb.html[Thumb] プロパティを使用して、単一値スライダーのつまみの値を取得できます。

link:{ApiPlatform}controls.editors.xamslider{ApiVersion}~infragistics.controls.editors.xamrangeslider`1~thumbs.html[Thumbs] コレクションにアクセスすることによって、範囲スライダーのつまみの値を取得できます。

xamSlider コントロールは ItemsControl から継承するので、インデックスを使用した場合に限りつまみにアクセスできます。つまみの名前でアクセスできません。

以下のコードはつまみの値を取得する方法を示します。

*Visual Basic の場合:*

----
' 単一値スライダー
Dim SingleValueSliderValue As Double = Me.xamNumericSlider1.Thumb.Value
' 範囲スライダー
Dim RangeSliderValue As Double = Me.xamNumericRangeSlider1.Thumbs(0).Value
' 単一値日時スライダー
Dim SingleValueDateTimeSlider As DateTime = Me.xamDateTimeSlider1.Thumb.Value
' 日時範囲スライダーの最初のつまみにアクセスします
Dim RangeDateTimeSlider As DateTime = Me.xamDateTimeRangeSlider1.Thumbs(0).Value
' 日時範囲スライダーの 2 番目のつまみにアクセスします
Dim RangeDateTimeSlider1 As DateTime = Me.xamDateTimeRangeSlider1.Thumbs(1).Value
----

*C# の場合:*

----
// 単一値スライダー
double SingleValueSliderValue = this.xamNumericSlider1.Thumb.Value;
// 範囲スライダーの最初のつまみにアクセスします
double RangeSliderValue = this.xamNumericRangeSlider1.Thumbs[0].Value;
// 範囲スライダーの 3 番目のつまみにアクセスします
double RangeSliderValue = this.xamNumericRangeSlider1.Thumbs[2].Value;
// 単一値日時スライダー
DateTime SingleValueDateTimeSlider = this.xamDateTimeSlider1.Thumb.Value;
// 日時範囲スライダーの最初のつまみにアクセスします
DateTime RangeDateTimeSlider = this.xamDateTimeRangeSlider1.Thumbs[0].Value;
// 日時範囲スライダーの 2 番目のつまみにアクセスします
DateTime RangeDateTimeSlider1 = this.xamDateTimeRangeSlider1.Thumbs[1].Value;
----

== 関連トピック

* link:xamslider-interaction-modes.html[操作モード]
* link:xamslider-xamslider-thumbs.html[xamSlider につまみを追加]
* link:xamslider-xamslider-tick-marks.html[目盛]
* link:xamslider-value-tick-marks.html[目盛値]
* link:xamslider-programmatically-add-or-remove-thumbs-at-runtime.html[プログラムによってランタイムでつまみを追加または削除]