////

|metadata|
{
    "name": "xamtagcloud",
    "controlName": ["xamTagCloud"],
    "tags": [],
    "guid": "{F56932BF-F375-4553-B49E-AECCED35A665}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.5223632Z"
}
|metadata|
////

= xamTagCloud

このセクションでは、xamTagCloud™ の使用に関する概要を説明します。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの xamTagCloud についての有益な情報を含んでいます。以下のリンクをクリックして、xamTagCloud コントロールについての情報にアクセスします。

== link:xamtagcloud-about-xamtagcloud.html[xamTagCloud について]

このセクションの説明を読むと、xamTagCloud コントロールの機能性と、それをアプリケーションに使用することの利点についてよく理解できます。

== link:xamtagcloud-adding-xamtagcloud-to-your-page.html[xamTagCloud をページに追加]

このトピックでは、プロシージャ コードおよび XAML を使用して xamTagCloud コントロールをページに追加する方法について説明します。

== link:xamtagcloud-binding-xamtagcloud-to-data.html[xamTagCloud をデータにバインド]

このトピックでは、プロシージャ コードおよび XAML を使用して xamTagCloud コントロールをデータにバインドする方法について説明します。

== link:xamtagcloud-using-xamtagcloud.html[xamTagCloud の使用]

このセクションには、xamTagCloud コントロールで提供される主要な特徴および機能についての情報が含まれています。

== link:xamtagcloud-api-overview.html[API の概要]

このトピックは、xamTagCloud コントロールを使用して開発する際の名前空間とクラスについて説明します。このトピックに挙げられている名前空間とクラスは、{ProductName} ヘルプの「API リファレンス ガイド」セクションにリンクされています。