= What's New in 2020 Volume 2

=== .NET 5.0 Support


A new environment to use Infragistics controls is now available! As of version 2020.2, our assemblies now have support for the .NET 5.0 environment through NuGet. 
NET 5.0 is the next major release of .NET Core following 3.1.

For some advantages of .NET 5.0, see link: https://docs.microsoft.com/en-us/dotnet/core/dotnet-five[This article on Microsoft's site].

You can read about configuring your environment to use Infragistics NuGet packages at our link:nuget-feeds.html[NuGet Feed] and link:nuget-packages.html[NuGet Packages] topics.


=== Support for new WPF Designers in Visual Studio 2019 Preview


Version 2020.2 of the Infragistics for WPF toolset now includes support for the new surface isolation designers for .NET Core and .NET Framework that are a preview feature included in Visual Studio 2019 Preview.

In order to enable the new preview designers, you need to opt in to this preview feature in Visual Studio 2019 Preview. To do this, you can follow the below steps:

- Open the Tools menu and click Options.
- In the resulting dialog, click the Preview Features menu item under the parent Environment item.
- In the Preview Features, there will be a checkbox for "New WPF XAML Designer for .NET." Checking this will enable usage of the new designers after a restart of Visual Studio 2019 Preview.

Regarding usage of these designers in .NET Core, you will need to add the Infragistics for WPF 2020.2 NuGet package in order to have the tools show up in the toolbox. You can read about configuring your environment to use Infragistics NuGet packages at our link:nuget-feeds.html[NuGet Feed] and link:nuget-packages.html[NuGet Packages] topics.