////
|metadata|
{
    "name": "xamcomboeditor-setting-the-xamcomboeditor-as-an-editor-of-a-field-programmatically",
    "controlName": ["xamComboEditor"],
    "tags": ["How Do I"],
    "guid": "{D9E6AB77-B21C-4968-BF2E-376DE7065A02}",
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1049781Z"
}
|metadata|
////

= Setting the xamComboEditor as an Editor of a Field Programmatically

== Before You Begin

You can use xamComboEditor™ to present your end users with a drop-down list of items within a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[Field] of xamDataGrid™. The recommended approach to populating xamComboEditor for use within xamDataGrid is to create the link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.comboboxitemsprovider.html[ComboBoxItemsProvider] object as a resource and then reference it using a markup extension. This pattern will keep overhead to a minimum by reusing a single instance of the ComboBoxItemsProvider object within a Field of xamDataGrid.

== What You Will Accomplish

You will set the editor of a Field to xamComboEditor using procedural code.

== Follow these Steps

[start=1]
. Attach an event handler for xamDataGrid's FieldLayoutInitialized event.

*In XAML:*
[source,xaml]
----
...
<igDP:XamDataGrid … FieldLayoutInitialized="XamDataGrid1_FieldLayoutInitialized" />
...
----

[start=2]
. Create a Resources section in your Window.

*In XAML:*
[source,xaml]
----
...
<Window.Resources>
</Window.Resources>
...
----

[start=3]
. Add a ComboBoxItemsProvider to the Resources section and give it a key so that you can reference it later.

*In XAML:*
[source,xaml]
----
...
<igEditors:ComboBoxItemsProvider x:Key="cbipRatings">
        <!--TODO: Add ComboBoxDataItems here-->
</igEditors:ComboBoxItemsProvider>
...
----

[start=4]
. Add five link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.comboboxdataitem.html[ComboBoxDataItem] objects to the Items collection of the ComboBoxItemsProvider object.

You will need to set the DisplayText property and Value property of each ComboBoxDataItem object. The DisplayText property will determine the text that the end user will see and the Value property will determine the value that is stored in the Cell's Value property as well as the underlying data model.

*In XAML:*
[source,xaml]
----
...
<igEditors:ComboBoxItemsProvider.Items>
        <igEditors:ComboBoxDataItem DisplayText="5 Stars" Value="5 Stars" />
        <igEditors:ComboBoxDataItem DisplayText="4 Stars" Value="4 Stars" />
        <igEditors:ComboBoxDataItem DisplayText="3 Stars" Value="3 Stars" />
        <igEditors:ComboBoxDataItem DisplayText="2 Stars" Value="2 Stars" />
        <igEditors:ComboBoxDataItem DisplayText="1 Star" Value="1 Star" />
</igEditors:ComboBoxItemsProvider.Items>
...
----

[start=5]
. Add using/Imports directives in your code-behind.

*In Visual Basic:*
[source,vb]
----
Imports Infragistics.Windows.DataPresenter
Imports Infragistics.Windows.Editors
----

*In C#:*
[source,csharp]
----
using Infragistics.Windows.DataPresenter;
using Infragistics.Windows.Editors;
----

[start=6]
. Create a method that will handle the FieldLayoutInitialized event.

*In Visual Basic:*
[source,vb]
----
Private Sub XamDataGrid1_FieldLayoutInitialized(ByVal sender As Object, _
  ByVal e As _
  Infragistics.Windows.DataPresenter.Events.FieldLayoutInitializedEventArgs) 
End Sub
----

*In C#:*
[source,csharp]
----
private void XamDataGrid1_FieldLayoutInitialized(object sender, 
  Infragistics.Windows.DataPresenter.Events.FieldLayoutInitializedEventArgs e)
{
}
----

[start=7]
. Create a `Field` object instance in the FieldLayoutInitialized event handler.

You should set the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fielditem~name.html[Name] property so that you can use it as a key to index into the Fields collection. You should also set the `BindingType` property to `Unbound`. You can also set the `Label` property to display text in the header above the Field.

*In Visual Basic:*
[source,vb]
----
Dim uField as New Field()
uField.Name = "rating"
uField.Label = "Rating"
uField.BindingType = BindingType.Unbound
----

*In C#:*
[source,csharp]
----
Field uField = new Field();
uField.Name = "rating";
uField.Label = "Rating";
uField.BindingType = BindingType.Unbound;
----

[start=8]
. Add the unbound field object to the Fields collection of the FieldLayout.

*In Visual Basic:*
[source,vb]
----
e.FieldLayout.Fields.Add(uField)
----

*In C#:*
[source,csharp]
----
e.FieldLayout.Fields.Add(uField);
----

[start=9]
. Create an instance of a Style object that targets the xamComboEditor.

*In Visual Basic:*
[source,vb]
----
Dim xamComboEditorStyle As New Style(GetType(XamComboEditor))
----

*In C#:*
[source,csharp]
----
Style xamComboEditorStyle = new Style(typeof(XamComboEditor));
----

[start=10]
. Create an instance of a Setter that sets the ItemsProviderProperty property of xamComboEditor to the ComboBoxItemsProvider resource you created in step three.

*In Visual Basic:*
[source,vb]
----
Dim itemsProviderSetter As New Setter(XamComboEditor.ItemsProviderProperty, Me.FindResource("cbipRatings"))
----

*In C#:*
[source,csharp]
----
Setter itemsProviderSetter = new Setter(XamComboEditor.ItemsProviderProperty, this.FindResource("cbipRatings"));
----

[start=11]
. Add the Setter object to the Setters collection of the Style object you created in step nine.

*In Visual Basic:*
[source,vb]
----
xamComboEditorStyle.Setters.Add(itemsProviderSetter)
----

*In C#:*
[source,csharp]
----
xamComboEditorStyle.Setters.Add(itemsProviderSetter);
----

[start=12]
. Set the EditorStyle property of the FieldSettings object off the unbound field to the Style you just created.

*In Visual Basic:*
[source,vb]
----
uField.Settings.EditorStyle = xamComboEditorStyle
----

*In C#:*
[source,csharp]
----
uField.Settings.EditorStyle = xamComboEditorStyle;
----

[start=13]
. Run the project. Click in a Cell in the Field labeled 'Rating' to edit the Cell's value using the xamComboEditor control.